Repository maistra/istio, pull requests merged in 2020-05, with the labels that each got.

#110 MAISTRA-1449 Update to 1.4.8
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  go.mod
  go.sum
  install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/role.yaml
  install/kubernetes/helm/istio/charts/gateways/templates/rolebindings.yaml
  istio.deps
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/core/v1alpha3/cluster_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  pilot/pkg/proxy/envoy/v2/ep_filters.go
  pilot/pkg/security/authz/model/principal.go
  pilot/pkg/security/authz/model/principal_test.go
  prow/lib.sh
  prow/release-commit.sh
  samples/security/psp/all-pods-psp.yaml
  tests/integration/security/rbac_v1beta1_test.go
  tests/integration/security/testdata/rbac/v1beta1-request-headers.yaml.tmpl
Labels: okay to merge, size/L

#105 MAISTRA-1368 Fix secure naming data structure always expanding, never shrinking
  pilot/pkg/proxy/envoy/v2/eds.go
  pilot/pkg/proxy/envoy/v2/eds_test.go
Labels: okay to merge, size/M

#111 MAISTRA-1451 Ensure the sidecar injector webhook applies podRedirectAnnot to pod
  pkg/kube/inject/testdata/webhook/TestWebhookInject_podRedirectAnnot.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_podRedirectAnnot.yaml
  pkg/kube/inject/testdata/webhook/TestWebhookInject_podRedirectAnnot_template.yaml
  pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
  pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
  pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
  pkg/kube/inject/testdata/webhook/frontend.yaml.injected
  pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
  pkg/kube/inject/testdata/webhook/hello-mtls-not-ready.yaml.injected
  pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
  pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
  pkg/kube/inject/testdata/webhook/job.yaml.injected
  pkg/kube/inject/testdata/webhook/list-frontend.yaml.injected
  pkg/kube/inject/testdata/webhook/list.yaml.injected
  pkg/kube/inject/testdata/webhook/multi-init.yaml.injected
  pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
  pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
  pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected
  pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
  pkg/kube/inject/testdata/webhook/status_annotations.yaml.injected
  pkg/kube/inject/testdata/webhook/traffic-annotations-empty-includes.yaml.injected
  pkg/kube/inject/testdata/webhook/traffic-annotations-wildcards.yaml.injected
  pkg/kube/inject/testdata/webhook/traffic-annotations.yaml.injected
  pkg/kube/inject/testdata/webhook/user-volume.yaml.injected
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
  sidecar-injector/cmd/sidecar-injector/main.go
Labels: okay to merge, size/L

#114 Allow limiting watched namespaces
  galley/pkg/config/source/kube/apiserver/options.go
  galley/pkg/config/source/kube/apiserver/source.go
  galley/pkg/config/source/kube/apiserver/status/controller_test.go
  galley/pkg/config/source/kube/rt/dynamic.go
  galley/pkg/config/source/kube/rt/known.go
  galley/pkg/config/source/kube/rt/provider.go
  galley/pkg/server/components/processing.go
  galley/pkg/server/settings/args.go
  mixer/adapter/kubernetesenv/cache.go
  mixer/cmd/mixs/cmd/server.go
  mixer/pkg/adapter/adapter.go
  mixer/pkg/adapter/test/env.go
  mixer/pkg/runtime/dispatcher/dispatcher_test.go
  mixer/pkg/runtime/handler/env.go
  mixer/pkg/runtime/handler/env_test.go
  mixer/pkg/runtime/handler/table.go
  mixer/pkg/runtime/handler/table_test.go
  mixer/pkg/runtime/routing/builder_test.go
  mixer/pkg/runtime/runtime.go
  mixer/pkg/runtime/runtime_test.go
  mixer/pkg/runtime/testing/data/adapters.go
  mixer/pkg/server/args.go
  mixer/pkg/server/server.go
  mixer/test/listbackend/list.go
  mixer/test/prometheus/nosession.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/controller/controller.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingress/status_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
  pkg/listwatch/listwatch.go
  pkg/listwatch/listwatch_test.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/registry/kube/service.go
  security/pkg/registry/kube/serviceaccount.go
Labels: okay to merge, size/XL
