Repository maistra/istio, pull requests merged in 2020-12, with the labels that each got.

#203 MAISTRA-1968 allow analyzer to work with multi list watcher
  galley/pkg/config/source/kube/apiserver/options.go
  galley/pkg/config/source/kube/apiserver/source.go
  galley/pkg/config/source/kube/rt/dynamic.go
  galley/pkg/server/components/processing.go
  galley/pkg/server/settings/args.go
  pilot/pkg/bootstrap/configcontroller.go
Labels: okay to merge, size/M

#216 add xuxa
  xuxa
Labels: okay to merge, size/XS

#217 change xuxa
  xuxa
Labels: okay to merge, size/XS

#219 x
  xuxa
Labels: okay to merge, size/XS

#200 MAISTRA-1958 Support JSON values in annotation k8s.v1.cni.cncf.io/networks
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/gen-istiod-remote.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.injected.yaml
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml
Labels: okay to merge, size/L
