Repository maistra/istio, pull requests merged in 2020-06, with the labels that each got.

#117 MAISTRA-1374: support multiple multus CNI interfaces
  install/kubernetes/helm/istio/files/injection-template.yaml
  install/kubernetes/helm/istio/values.yaml
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello.yaml.cni_network
  pkg/kube/inject/testdata/inject/hello.yaml.cni_network.injected
Labels: okay to merge, size/L

#109 MAISTRA-1398: Address pilot failure when merging filter chains
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: okay to merge, size/M

#124 Run sidecars with dynamically-determined user IDs
  pkg/kube/inject/inject.go
  pkg/kube/inject/testdata/webhook/TestWebhookInject.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_nosidecar_rewrite.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_disabled_via_annotation.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_enabled_via_annotation.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_https_probe_rewrite.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_injectorAnnotations.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_mtls_not_ready.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers_volumes.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers_volumes_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_containers.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_containers_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_containers_volumes.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_volumes.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_volumes_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initcontainers_containers_volumes_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_volumes.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_volumes_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_probe_rewrite_timeout_retention.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_replace.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_replace_backwards_compat.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_validationOrder.patch
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
  pkg/test/framework/components/echo/kube/deployment.go
  pkg/test/framework/components/echo/kube/testdata/basic.yaml
  pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
  pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
  pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
Labels: size/L

#125 Ensure Pilot can run without privileges for reading nodes
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
Labels: size/L

#126 MAISTRA-417: Dynamic namespace support in multi-tenancy
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/servicecontroller.go
  pilot/pkg/config/kube/crd/controller/controller.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingress/status_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pilot/pkg/serviceregistry/kube/controller/pod_test.go
Labels: size/L

#128 MAISTRA-417: Add support for dynamic namespaces in Galley
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
  galley/pkg/config/source/kube/apiserver/source.go
  galley/pkg/config/source/kube/apiserver/source_dynamic_test.go
  galley/pkg/config/source/kube/apiserver/status/controller_test.go
  galley/pkg/config/source/kube/apiserver/watcher.go
  galley/pkg/config/source/kube/rt/dynamic.go
  galley/pkg/config/source/kube/rt/known.go
  galley/pkg/config/source/kube/rt/provider.go
  galley/pkg/server/components/processing.go
  galley/pkg/server/settings/args.go
  pilot/pkg/bootstrap/configcontroller.go
Labels: size/M

#129 MAISTRA-1451: Ensure the sidecar injector webhook applies podRedirectAnnot to pod
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/bootstrap/sidecarinjector.go
  pkg/kube/inject/testdata/webhook/TestWebhookInject_podRedirectAnnot.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_podRedirectAnnot.yaml
  pkg/kube/inject/testdata/webhook/TestWebhookInject_podRedirectAnnot_template.yaml
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: size/L

#130 MAISTRA-443: Add support for dynamic namespaces in mixer
  mixer/cmd/mixs/cmd/server.go
  mixer/pkg/runtime/dispatcher/dispatcher_test.go
  mixer/pkg/runtime/handler/env.go
  mixer/pkg/runtime/handler/env_test.go
  mixer/pkg/runtime/handler/table.go
  mixer/pkg/runtime/handler/table_test.go
  mixer/pkg/runtime/routing/builder_test.go
  mixer/pkg/runtime/runtime.go
  mixer/pkg/runtime/runtime_test.go
  mixer/pkg/server/args.go
  mixer/pkg/server/server.go
  mixer/test/listbackend/list.go
  mixer/test/prometheus/nosession.go
Labels: size/L

#131 MAISTRA-224: Support for authz regex matching on request headers
  pilot/pkg/security/authz/matcher/header.go
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
  pilot/pkg/security/authz/model/model.go
Labels: size/M

#132 Changes required for dynamic namespace support in Chiron
  pilot/pkg/bootstrap/certcontroller.go
  security/cmd/chiron/main.go
  security/pkg/cmd/constants.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/k8s/chiron/controller_test.go
  security/pkg/k8s/chiron/utils_test.go
  security/pkg/registry/kube/service.go
  security/pkg/registry/kube/service_test.go
  security/pkg/registry/kube/serviceaccount.go
  security/pkg/registry/kube/serviceaccount_test.go
Labels: size/M
