Repository maistra/istio, pull requests merged in 2020-03, with the labels that each got.

#83 MAISTRA-1239 Fix rebase artifact
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge

#80 MAISTRA-1203 Fix failing integration tests
  galley/testdata/validation/dataset.gen.go
  galley/testdata/validation/dataset/authentication-v1alpha1-ServiceMeshPolicy-invalid.yaml
  galley/testdata/validation/dataset/authentication-v1alpha1-ServiceMeshPolicy-valid.yaml
  galley/testdata/validation/dataset/rbac-v1alpha1-ServiceMeshRbacConfig-invalid.yaml
  galley/testdata/validation/dataset/rbac-v1alpha1-ServiceMeshRbacConfig-valid.yaml
  samples/bookinfo/platform/kube/rbac/rbac-config-ON.yaml
  samples/bookinfo/platform/kube/rbac/rbac-config-on-mongodb.yaml
  samples/bookinfo/platform/kube/rbac/rbac-config-on-permissive.yaml
  tests/integration/conformance/testdata/authentication/meshpolicy/basic/input.yaml
  tests/integration/conformance/testdata/authentication/meshpolicy/basic/mcp.yaml
  tests/integration/conformance/testdata/rbac/clusterRbacConfig/basic/input.yaml
  tests/integration/conformance/testdata/rbac/clusterRbacConfig/basic/mcp.yaml
  tests/integration/pilot/outboundtrafficpolicy/allowany/traffic_allow_any_test.go
  tests/integration/pilot/ping_test.go
  tests/integration/pilot/protocol_sniffing_test.go
  tests/integration/security/mtls/testdata/global-mtls-on-no-dr.yaml
  tests/integration/security/mtls/testdata/global-plaintext.yaml
  tests/integration/security/reachability_test.go
  tests/integration/security/testdata/rbac/v1-policy-path.yaml.tmpl
Labels: okay to merge

#84 MAISTRA-1203 Fix failing integration tests
  galley/testdata/validation/dataset.gen.go
  galley/testdata/validation/dataset/authentication-v1alpha1-ServiceMeshPolicy-invalid.yaml
  galley/testdata/validation/dataset/authentication-v1alpha1-ServiceMeshPolicy-valid.yaml
  galley/testdata/validation/dataset/rbac-v1alpha1-ServiceMeshRbacConfig-invalid.yaml
  galley/testdata/validation/dataset/rbac-v1alpha1-ServiceMeshRbacConfig-valid.yaml
  samples/bookinfo/platform/kube/rbac/rbac-config-ON.yaml
  samples/bookinfo/platform/kube/rbac/rbac-config-on-mongodb.yaml
  samples/bookinfo/platform/kube/rbac/rbac-config-on-permissive.yaml
  tests/integration/conformance/testdata/authentication/meshpolicy/basic/input.yaml
  tests/integration/conformance/testdata/authentication/meshpolicy/basic/mcp.yaml
  tests/integration/conformance/testdata/rbac/clusterRbacConfig/basic/input.yaml
  tests/integration/conformance/testdata/rbac/clusterRbacConfig/basic/mcp.yaml
  tests/integration/pilot/outboundtrafficpolicy/allowany/traffic_allow_any_test.go
  tests/integration/pilot/ping_test.go
  tests/integration/pilot/protocol_sniffing_test.go
  tests/integration/security/mtls/testdata/global-mtls-on-no-dr.yaml
  tests/integration/security/mtls/testdata/global-plaintext.yaml
  tests/integration/security/reachability_test.go
  tests/integration/security/testdata/rbac/v1-policy-path.yaml.tmpl
Labels: okay to merge

#85 MAISTRA-322: Include gRPC status as 'response_code' label for prometh…
  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml
  pkg/bootstrap/testdata/all_golden.json
  pkg/bootstrap/testdata/auth_golden.json
  pkg/bootstrap/testdata/authsds_golden.json
  pkg/bootstrap/testdata/default_golden.json
  pkg/bootstrap/testdata/running_golden.json
  pkg/bootstrap/testdata/runningsds_golden.json
  pkg/bootstrap/testdata/stats_inclusion_golden.json
  pkg/bootstrap/testdata/tracing_datadog_golden.json
  pkg/bootstrap/testdata/tracing_lightstep_golden.json
  pkg/bootstrap/testdata/tracing_stackdriver_golden.json
  pkg/bootstrap/testdata/tracing_zipkin_golden.json
  tools/packaging/common/envoy_bootstrap_v2.json
Labels: okay to merge

#86 MAISTRA-329 Add proxyCPULimit/proxyMemoryLimit to injection template
  install/kubernetes/helm/istio/files/injection-template.yaml
Labels: okay to merge

#88 MAISTRA-1258 Don't Run() citadel's namespaceController
  security/pkg/k8s/controller/workloadsecret.go
Labels: okay to merge, size/XS

#94 fix http to https redirection during container build for testing
  pilot/docker/Dockerfile.proxy_debug
  pilot/docker/Dockerfile.proxytproxy
  pilot/docker/Dockerfile.proxyv2
Labels: okay to merge, size/XS

#93 MAISTRA-1285 resign certificate (#22123)
  tests/testdata/certs/default/cert-chain.pem
  tests/testdata/certs/default/key.pem
  tests/testdata/certs/default/root-cert.pem
  tests/testdata/certs/pilot/cert-chain.pem
  tests/testdata/certs/pilot/key.pem
  tests/testdata/certs/pilot/root-cert.pem
  tests/testdata/local/etc/certs/cert-chain.pem
  tests/testdata/local/etc/certs/key.pem
  tests/testdata/local/etc/certs/root-cert.pem
Labels: okay to merge, size/L
