Repository maistra/istio, pull requests merged in 2020-07, with the labels that each got.

#137 MAISTRA-1643: Bump to upstream Istio 1.6.5
  Makefile.core.mk
  bin/protoc.sh
  common/.commonfiles.sha
  common/Makefile.common.mk
  go.mod
  go.sum
  install/gcp/bootstrap/gcp_envoy_bootstrap.json
  istio.deps
  istioctl/pkg/validate/validate.go
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
  manifests/charts/istio-control/istio-discovery/templates/service.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
  mixer/adapter/kubernetesenv/cache.go
  mixer/adapter/kubernetesenv/cache_test.go
  mixer/pkg/attribute/generate_word_list.sh
  operator/cmd/mesh/manifest-generate_test.go
  operator/cmd/mesh/profile-common.go
  operator/cmd/mesh/testdata/manifest-generate/input/pilot_override_kubernetes.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
  operator/cmd/mesh/testdata/manifest-migrate/output/default_values.golden.yaml
  operator/pkg/component/component.go
  operator/pkg/controlplane/control_plane_test.go
  operator/pkg/translate/translate.go
  operator/pkg/translate/translate_value.go
  operator/pkg/translate/translate_value_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pkg/config/mesh/mesh.go
  pkg/istio-agent/sds-agent.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/status_annotations_zeroport.yaml
  pkg/kube/inject/testdata/inject/status_annotations_zeroport.yaml.injected
  pkg/test/echo/server/endpoint/grpc.go
  prow/release-commit.sh
  tools/istio-docker.mk
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
  tools/packaging/common/envoy_bootstrap_v2.json
  vendor/istio.io/api/mesh/v1alpha1/config.pb.go
  vendor/istio.io/api/mesh/v1alpha1/config.proto
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  vendor/istio.io/api/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.gen.json
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/operator/v1alpha1/component.pb.go
  vendor/istio.io/api/operator/v1alpha1/component.proto
  vendor/istio.io/api/operator/v1alpha1/istio.operator.v1alpha1.pb.html
  vendor/modules.txt
Labels: don't squash, okay to merge, size/XL

#120 MAISTRA-1541: Fix panic when controller not set
  mixer/adapter/kubernetesenv/cache.go
  mixer/adapter/kubernetesenv/cache_test.go
Labels: okay to merge, size/M

#123 MAISTRA-1301 Make sure integration tests run with latest toolchain
  prow/lib.sh
  tests/integration/tests.mk
  vendor/istio.io/operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  vendor/istio.io/operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  vendor/istio.io/operator/pkg/apis/istio/v1alpha1/values_types.proto
  vendor/istio.io/operator/pkg/vfs/assets.gen.go
  vendor/modules.txt
Labels: okay to merge, size/M

#139 MAISTRA-1642: Add support for proxy env annotation
  install/kubernetes/helm/istio/files/injection-template.yaml
  pkg/kube/inject/testdata/webhook/maistra_env_annotations.yaml
  pkg/kube/inject/testdata/webhook/maistra_env_annotations.yaml.injected
  pkg/kube/inject/webhook_test.go
Labels: okay to merge, size/L

#142 MAISTRA-1649: Enable multiple listeners for Unsupported headless serv…
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: okay to merge, size/M

#144 MAISTRA-1666: Add `go mod vendor` as part of `make gen`
  pkg/servicemesh/maistra.mk
Labels: okay to merge, size/XS

#143 MAISTRA-1665 Support JSON values in annotation k8s.v1.cni.cncf.io/networks
  install/kubernetes/helm/istio/files/injection-template.yaml
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello.yaml.cni_network_json
  pkg/kube/inject/testdata/inject/hello.yaml.cni_network_json.injected
Labels: okay to merge, size/L

#145 MAISTRA-1456: Add support for minimum and maximum TLS protocol versions
  galley/pkg/crd/validation/webhook.go
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/security/authn/v1alpha1/policy_applier.go
  pilot/pkg/security/authn/v1alpha1/policy_applier_test.go
  pkg/features/tls_protocol_version.go
  pkg/kube/inject/webhook.go
Labels: size/L

#146 MAISTRA-1681: Do not define env unless one of the TLS variables is be…
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: size/XS

#148 MAISTRA-1692: Move env section before args
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
Labels: okay to merge, size/S

#149 MAISTRA-1697: prevent warning when specifying TLS_AUTO
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: okay to merge, size/XS

#150 MAISTRA-1698: tidy up tlsProtocolVersion
  galley/pkg/crd/validation/webhook.go
  pilot/pkg/bootstrap/server.go
  pkg/features/tls_protocol_version.go
  pkg/kube/inject/webhook.go
Labels: size/S

#151 MAISTRA-1699: Add support for configuring cipher suites
  galley/pkg/crd/validation/webhook.go
  install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
  install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/deployment.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/security/authn/v1alpha1/policy_applier.go
  pilot/pkg/security/authn/v1alpha1/policy_applier_test.go
  pkg/features/tls_cipher_suites.go
  pkg/kube/inject/webhook.go
Labels: size/L
