Repository maistra/istio, pull requests merged in 2020-04, with the labels that each got.

#97 MAISTRA-1206 Fix refreshing of DNS secrets
  security/pkg/k8s/chiron/controller.go
Labels: okay to merge, size/S

#98 MAISTRA-1305 Fix broken security integration tests
  tests/integration/istioio/security/authz_http_test.go
  tests/integration/security/rbac_v1alpha1_test.go
  tests/integration/security/testdata/global-mtls-off.yaml
  tests/integration/security/testdata/global-mtls-on.yaml
  tests/integration/security/testdata/global-mtls-permissive.yaml
  tests/integration/security/testdata/rbac/clusterrbacconfig.yaml
  tests/integration/security/testdata/rbac/v1-policy-path.yaml.tmpl
  tests/integration/security/testdata/rbac/v1beta1-override-v1alpha1.yaml.tmpl
Labels: okay to merge, size/M

#101 Add "don't squash" label handling to .mergify.yml
  .mergify.yml
Labels: size/M
