Repository maistra/istio, pull requests merged in 2020-10, with the labels that each got.

#184 Add bin/update_proxy.sh
  bin/update_proxy.sh
Labels: okay to merge, size/M

#183 MAISTRA-1862 Fix NilPointerException when images can't be pulled
  mec/pkg/model/types.go
  mec/pkg/pullstrategy/ossm/strategy.go
  mec/pkg/server/worker.go
Labels: okay to merge, size/M

#182 MAISTRA-1873 Properly delete extensions from store when they disappear
  pkg/servicemesh/controller/extension/controller.go
Labels: okay to merge, size/XS

#186 MAISTRA-1856: Disable ClusterRbacConfig resources
  galley/testdatasets/validation/dataset.gen.go
  galley/testdatasets/validation/dataset/rbac-v1alpha1-ClusterRbacConfig-invalid.yaml
  galley/testdatasets/validation/dataset/rbac-v1alpha1-ClusterRbacConfig-valid.yaml
  pilot/pkg/config/kube/crd/types.gen.go
  pilot/pkg/model/config.go
  pilot/pkg/model/config_test.go
  pilot/pkg/model/push_context.go
  pilot/pkg/networking/core/v1alpha3/fakes/fake_istio_config_store.gen.go
  pilot/pkg/proxy/envoy/v2/ads_common.go
  pilot/test/mock/config.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.gen.go
  pkg/config/schema/metadata.yaml
  tests/integration/conformance/testdata/rbac/clusterRbacConfig/basic/input.yaml
  tests/integration/conformance/testdata/rbac/clusterRbacConfig/basic/mcp.yaml
  tests/integration/conformance/testdata/rbac/clusterRbacConfig/basic/test.yaml
Labels: okay to merge, size/M

#185 MAISTRA-1686: Update proxy SHA to ours
  istio.deps
  pilot/docker/Dockerfile.proxyv2
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
Labels: okay to merge, size/M

#188 MAISTRA-1897: Allow disabling IngressClass support
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge, size/S

#189 MAISTRA-1908: Fix tombstone handling in endpoints controller
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Labels: okay to merge, size/XS

#187 MAISTRA-1895 Add option to enable/disable CRD scan
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/config/kube/crd/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge, size/S

#190 MAISTRA-1811 Store resourceVersion of reconciled Gateway resource
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/L

#193 MAISTRA-1089 Add support for IOR routes in all namespaces
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/M

#192 MAISTRA-1931 implement multi list watcher for mixer
  mixer/pkg/config/crd/init.go
  mixer/pkg/config/crd/store.go
  mixer/pkg/config/crd/store_test.go
  mixer/pkg/config/mcp/backend.go
  mixer/pkg/config/store/store.go
  mixer/pkg/config/store/store_test.go
  mixer/pkg/server/server.go
Labels: okay to merge, size/L

#194 MAISTRA-1038 Add support for new node topology labels
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
Labels: okay to merge, size/S

#191 MAISTRA-1924 Fix handling of resource deletions
  pilot/pkg/config/kube/crd/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
Labels: okay to merge, size/M

#195 MAISTRA-1779: Fix ledger capacity size
  pilot/pkg/status/reporter.go
Labels: okay to merge, size/XS

#197 MAISTRA-1937 Move ServiceMeshExtension to maistra.io apiGroup
  mec/deploy/example.yaml
  mec/deploy/mec.yaml
  pkg/servicemesh/apis/servicemesh/v1alpha1/register.go
Labels: okay to merge, size/XS
