Repository maistra/istio, pull requests merged in 2020-08, with the labels that each got.

#164 MAISTRA-1754 Set CNI container tag to 1.6-dev instead of latest
  tests/integration/pilot/cni/cni_test.go
Labels: okay to merge, size/XS

#162 MAISTRA-1751 Set securityContext.fsGroup to comply with restricted SCC
  pkg/kube/inject/webhook.go
Labels: okay to merge, size/M

#161 MAISTRA-1724 Don't watch namespaces if MRC is used
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
Labels: okay to merge, size/M

#165 MAISTRA-1612 Remove injectPodRedirectAnnot option and always inject them
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/bootstrap/sidecarinjector.go
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: okay to merge, size/S

#158 [MAISTRA-1744] Add route annotation propagation
  pilot/pkg/config/kube/ior/route.go
Labels: ok-to-test, okay to merge, size/S

#159 MAISTRA-1741 Store resourceVersions locally instead of returning them
  pkg/listwatch/listwatch.go
  pkg/listwatch/listwatch_test.go
Labels: okay to merge, size/M

#169 MAISTRA-1755 invoke UpdateNamespaces() as part of MemberRollControlle…
  galley/pkg/config/source/kube/rt/dynamic.go
  galley/pkg/config/source/kube/rt/known.go
  mixer/pkg/runtime/handler/env.go
  pilot/pkg/config/kube/crd/controller/controller.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pkg/servicemesh/controller/controller.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/registry/kube/service.go
  security/pkg/registry/kube/serviceaccount.go
Labels: okay to merge, size/M

#157 MAISTRA-1739 Fix validation of AuthorizationPolicy fields
  pilot/pkg/security/authz/builder/testdata/v1beta1/all-fields-in.yaml
  pilot/pkg/security/authz/builder/testdata/v1beta1/all-fields-out.yaml
  pkg/config/security/security.go
Labels: okay to merge, size/M

#172 MAISTRA-1783 maistra istio samples yaml files need sidecar injection for testing
  samples/httpbin/httpbin.yaml
  samples/httpbin/sample-client/fortio-deploy.yaml
  samples/https/nginx-app.yaml
  samples/sleep/sleep.yaml
Labels: okay to merge, size/XS
