Repository maistra/istio, pull requests merged in 2021-12, with the labels that each got.

#455 Disable failing integration tests (until OSSM-755 is fixed)
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
Labels: okay to merge, size/S

#456 OSSM-774 Fix flaky TestStatusManager
  pkg/servicemesh/federation/status/manager_test.go
Labels: okay to merge, size/XS

#446 MAISTRA-2703 Rebase to Istio 1.9.9
  Makefile.core.mk
  docker/Dockerfile.distroless
  go.mod
  go.sum
  pilot/cmd/pilot-agent/main.go
  pilot/pkg/xds/ads.go
  pilot/pkg/xds/lds.go
  pilot/pkg/xds/pushqueue.go
  pilot/pkg/xds/pushqueue_test.go
  pkg/queue/instance.go
  pkg/security/security.go
  prow/release-commit.sh
  releasenotes/notes/34944.yaml
  releasenotes/notes/pq-memory-leak.yaml
  security/pkg/nodeagent/cache/secretcache.go
  tests/util/leak/check.go
  vendor/modules.txt
Labels: okay to merge, size/L, merge strategy

#444 MAISTRA-2704 Print version when istiod starts
  pilot/cmd/pilot-discovery/main.go
Labels: okay to merge, size/XS

#461 OSSM-870 Fix ApplyServiceMeshCRDs function
  bin/update_maistra_deps.sh
  tests/integration/servicemesh/util.go
Labels: okay to merge, size/M
