Repository maistra/istio, pull requests merged in 2021-06, with the labels that each got.

#354 MAISTRA-2391: Push old extension config
  pkg/servicemesh/extension/apply_extension.go
Labels: okay to merge, size/M

#348 MAISTRA-2309 create CRD for FederationStatus
  bin/update_maistra_deps.sh
  manifests/charts/base/crds/maistra.io_federationstatuses.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/crds.yaml
  manifests/charts/base/templates/role.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/discovery/controller_test.go
  pkg/servicemesh/federation/discovery/discovery.go
  pkg/servicemesh/federation/federation.go
  pkg/servicemesh/federation/server/server.go
  pkg/servicemesh/federation/server/server_test.go
  pkg/servicemesh/federation/status/handler.go
  pkg/servicemesh/federation/status/manager.go
  pkg/servicemesh/federation/status/manager_test.go
Labels: okay to merge, size/XXL

#359 MAISTRA-2251: Update SME status upon failures
  go.sum
  mec/pkg/server/worker.go
  mec/pkg/server/worker_test.go
Labels: okay to merge, size/L

#362 MAISTRA-2412 Fix ensureNamespaceExists() in ior/route.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/S

#361 MAISTRA-2249: Remove outdated comment
  mec/pkg/server/worker.go
Labels: okay to merge, size/XS

#357 MAISTRA-2390 Push trust bundle updates through xDS
  pilot/pkg/bootstrap/server.go
  pilot/pkg/xds/tbds.go
  pilot/pkg/xds/v3/model.go
  pkg/istio-agent/xds_proxy.go
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/federation.go
  pkg/servicemesh/federation/model/model.go
  security/pkg/nodeagent/cache/secretcache.go
  security/pkg/nodeagent/caclient/providers/citadel/client.go
Labels: okay to merge, size/L

#352 MAISTRA-2389: Ensure the status code can handle Forbidden errors
  pilot/pkg/status/state.go
Labels: okay to merge, size/XS

#371 Fix flaky Test_SecretController()
  pkg/kube/secretcontroller/secretcontroller_test.go
Labels: okay to merge, rebase to 1.9, size/XS

#378 MAISTRA-2441: Restore proxyEnv support
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/flag_set_values.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/maistra_env_annotations.yaml
  pkg/kube/inject/testdata/inject/maistra_env_annotations.yaml.injected
Labels: okay to merge, size/L

#363 MAISTRA-2254: MEC: Garbage collects Image Streams
  mec/pkg/model/interfaces.go
  mec/pkg/pullstrategy/fake/strategy.go
  mec/pkg/pullstrategy/ossm/strategy.go
  mec/pkg/pullstrategy/ossm/strategy_test.go
  mec/pkg/server/worker.go
Labels: okay to merge, size/M
