Repository maistra/istio, pull requests merged in 2021-09, with the labels that each got.

#421 MAISTRA-2611 Fix deletion of service exports to federated mesh
  pkg/servicemesh/federation/server/server.go
  pkg/servicemesh/federation/server/server_test.go
Labels: okay to merge, size/M

#433 MAISTRA-2639 Fix multi-root support
  pkg/istio-agent/xds_proxy.go
Labels: okay to merge, size/XS

#432 MAISTRA-2439: Prevent federation from exporting services that are not visible to the federation gateway
  pkg/servicemesh/federation/server/server.go
  pkg/servicemesh/federation/server/server_test.go
Labels: okay to merge, size/L

#425 MAISTRA-2617: Do not watch all namespaces in Extensions controller
  pkg/servicemesh/controller/extension/controller.go
Labels: okay to merge, size/XS

#434 MAISTRA-2649: Update the config map when it already exists
  security/pkg/k8s/configutil.go
Labels: okay to merge, size/S

#436 MAISTRA-2655: Fix the DNS capture with CNI
  cni/cmd/istio-cni/iptables.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
Labels: okay to merge, size/M

#437 MAISTRA-2658 Ensure ImportedServiceSet.status.importedServices is never nil
  pkg/servicemesh/federation/status/handler.go
  pkg/servicemesh/federation/status/manager_test.go
Labels: okay to merge, size/S

#439 MAISTRA-2682 Fix watch mechanism in federation
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/server/server.go
  pkg/servicemesh/federation/status/handler.go
Labels: okay to merge, size/M

#440 MAISTRA-2683 Properly close incoming watch connections when shutting down
  pkg/servicemesh/federation/server/server.go
Labels: okay to merge, size/XS

#441 Log actual error returned by pollServices()
  pilot/pkg/serviceregistry/federation/controller.go
Labels: okay to merge, size/XS
