Repository maistra/istio, pull requests merged in 2021-02, with the labels that each got.

#254 MAISTRA-2051: Use MultiNamespaceInformer in galley
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
  galley/pkg/config/source/kube/apiserver/options.go
  galley/pkg/config/source/kube/apiserver/source.go
  galley/pkg/config/source/kube/apiserver/source_builtin_test.go
  galley/pkg/config/source/kube/apiserver/source_dynamic_test.go
  galley/pkg/config/source/kube/apiserver/status/controller_test.go
  galley/pkg/config/source/kube/rt/dynamic.go
  galley/pkg/config/source/kube/rt/known.go
  galley/pkg/config/source/kube/rt/provider.go
  galley/pkg/server/components/processing.go
  galley/pkg/server/components/processing_test.go
  galley/pkg/server/settings/args.go
  istioctl/cmd/analyze.go
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/kube/client.go
  pkg/test/kube/mock_client.go
  tools/bug-report/pkg/content/content.go
Labels: okay to merge, size/XL

#236 [MAISTRA-224][MAISTRA-2010]: Support for authz regex matching on request headers
  pilot/pkg/security/authz/builder/testdata/all-fields-in.yaml
  pilot/pkg/security/authz/builder/testdata/all-fields-out.yaml
  pilot/pkg/security/authz/matcher/header.go
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
  pilot/pkg/security/authz/model/model.go
  pkg/config/security/security.go
  pkg/config/security/security_test.go
Labels: okay to merge, size/L

#242 MAISTRA-2105 Use -w flag when running iptables commands
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-iptables/pkg/builder/iptables_builder_impl.go
  tools/istio-iptables/pkg/builder/iptables_builder_test.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
Labels: okay to merge, size/XL

#255 MAISTRA-2051: Allow istiod to run without Node access
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingress/status_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge, size/M

#256 MAISTRA-1751: Set securityContext.fsGroup to comply with restricted SCC
  pkg/kube/inject/webhook.go
Labels: okay to merge, size/S

#257 MAISTRA-1724: Don't watch namespaces if MemberRoll is used
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
Labels: okay to merge, size/M

#258 MAISTRA-2051: Cherry-picks for Maistra 2.1 / Istio 1.8 rebase
  galley/pkg/config/source/kube/apiserver/source.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pkg/kube/client.go
  pkg/servicemesh/controller/controller.go
Labels: don't squash, okay to merge, size/M

#261 MAISTRA-1963: Skip privileged ports for non-root gateways
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener_test.go
Labels: okay to merge

#260 MAISTRA-1895: Add option to enable/disable CRD scan
  pilot/pkg/config/kube/crdclient/client.go
Labels: okay to merge, size/XS

#263 MAISTRA-1897: Allow disabling IngressClass support
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge, size/S

#240 [MAISTRA-1089][MAISTRA-1400][MAISTRA-1744][MAISTRA-1811]: Add IOR to Pilot (#135)
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/route.go
  pilot/pkg/features/pilot.go
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/legacy.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route_client.go
  vendor/modules.txt
Labels: okay to merge, size/XXL

#267 MAISTRA-2128: Fix flaky TestClientNoCRDs
  pilot/pkg/config/kube/crdclient/client_test.go
Labels: okay to merge, size/XS

#271 MAISTRA-2132 Support deployment of multiple plugin versions in Istio CNI
  cni/pkg/install-cni/cmd/root.go
  cni/pkg/install-cni/pkg/config/config.go
  cni/pkg/install-cni/pkg/constants/constants.go
  cni/pkg/install-cni/pkg/install/binaries.go
  cni/pkg/install-cni/pkg/install/install.go
Labels: okay to merge, size/M

#270 MAISTRA-2051: Add extended TLS options
  manifests/charts/global.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  operator/pkg/validate/validate_test.go
  operator/pkg/validate/validate_values_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/webhook.go
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pkg/features/tls_cipher_suites.go
  pkg/features/tls_ecdh_curves.go
  pkg/features/tls_protocol_version.go
Labels: don't squash, okay to merge, size/XL

#273 MAISTRA-2137 Make network namespace setup executable name configurable
  cni/cmd/istio-cni/main.go
Labels: okay to merge, size/XS

#272 MAISTRA-2140: Don't use pre-compiled WASM extensions
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
  manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.8.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.7.yaml
  manifests/charts/istiod-remote/templates/telemetryv2_1.8.yaml
Labels: okay to merge, size/L

#269 MAISTRA-2131: ior: honor Gateway's httpsRedirect
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/XS

#279 MAISTRA-2150: Prevent deadlock, do not hold edsClusterMutex when load…
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: okay to merge, size/S

#276 MAISTRA-2131: ior: honor Gateway's httpsRedirect
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/XS
