Repository maistra/istio, pull requests merged in 2021-08, with the labels that each got.

#414 Increase timeout to 5 minutes to make it pass on slow envs
  pkg/servicemesh/federation/example/config-poc/install.sh
Labels: ok-to-test, okay to merge, size/XS

#418 MAISTRA-2472 allow DefaultKubernetesAudience to be configurable
  pkg/security/security.go
  security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
Labels: okay to merge, size/S

#419 MAISTRA-2587 initialize mesh2 port env variables in federation demo s…
  pkg/servicemesh/federation/example/config-poc/install.sh
Labels: okay to merge, size/XS
