Repository maistra/istio, pull requests merged in 2021-04, with the labels that each got.

#300 MAISTRA-2057 Add missing _affinity.tpl to the istio-control helm templates
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/_affinity.tpl
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
Labels: okay to merge, size/L

#292 MAISTRA-2194 && MAISTRA-2195 Federation Service Discovery v1 (incl. /watch endpoint)
  go.mod
  go.sum
  licenses/github.com/mitchellh/hashstructure/v2/LICENSE
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/multicluster.go
  pilot/pkg/bootstrap/options.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/serviceregistry/federation/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/providers.go
  pkg/servicemesh/federation/model.go
  pkg/servicemesh/federation/server.go
  pkg/servicemesh/federation/server_test.go
  vendor/github.com/mitchellh/hashstructure/v2/LICENSE
  vendor/github.com/mitchellh/hashstructure/v2/README.md
  vendor/github.com/mitchellh/hashstructure/v2/errors.go
  vendor/github.com/mitchellh/hashstructure/v2/go.mod
  vendor/github.com/mitchellh/hashstructure/v2/hashstructure.go
  vendor/github.com/mitchellh/hashstructure/v2/include.go
  vendor/modules.txt
Labels: don't squash, okay to merge, size/XXL

#307 MAISTRA-681: Rewrite multi-namespace listwatcher to address performan…
  galley/pkg/source/kube/builtin/source_test.go
  galley/pkg/source/kube/builtin/types.go
  galley/pkg/source/kube/dynamic/source.go
  galley/pkg/source/kube/dynamic/source_test.go
  mixer/pkg/adapter/test/env.go
  mixer/pkg/runtime/handler/env.go
  pilot/pkg/config/kube/crd/controller/controller.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/listwatch/listinformer.go
  pkg/listwatch/listinformer_test.go
  pkg/listwatch/listlenlisterwatcher.go
  pkg/listwatch/listwatch.go
  pkg/listwatch/listwatch_test.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/k8s/controller/workloadsecret.go
  security/pkg/registry/kube/service.go
  security/pkg/registry/kube/serviceaccount.go
Labels: okay to merge, size/XXL

#305 MAISTRA-2246: Rewrite multi-namespace listwatcher to address performa…
  galley/pkg/config/source/kube/apiserver/source_builtin_test.go
  galley/pkg/config/source/kube/rt/dynamic.go
  galley/pkg/config/source/kube/rt/known.go
  mixer/pkg/adapter/test/env.go
  mixer/pkg/config/crd/store.go
  mixer/pkg/runtime/handler/env.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/controller/controller.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/endpoints.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/pod.go
  pkg/listwatch/listinformer.go
  pkg/listwatch/listinformer_test.go
  pkg/listwatch/listlenlisterwatcher.go
  pkg/listwatch/listwatch.go
  pkg/listwatch/listwatch_test.go
  pkg/servicemesh/controller/extension/controller.go
  security/pkg/k8s/chiron/controller.go
  security/pkg/registry/kube/service.go
  security/pkg/registry/kube/serviceaccount.go
Labels: okay to merge, size/XXL

#308 MAISTRA-2234: Seed MemberRoll listeners with system namespace
  pkg/servicemesh/controller/memberroll/controller.go
Labels: okay to merge, size/M

#311 MAISTRA-2255: Make sure IOR respond to all events
  pilot/pkg/config/kube/ior/client.go
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
Labels: don't squash, okay to merge, size/L

#313 MAISTRA-2269: Increase hardcoded QPS/Burst to a more reasonable limit
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/controller/client.go
  pilot/pkg/features/pilot.go
Labels: okay to merge, size/S

#314 MAISTRA-2270: Increase hardcoded QPS/Burst to a more reasonable limit
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/controller/client.go
  pilot/pkg/features/pilot.go
  pkg/kube/config.go
Labels: okay to merge, size/M

#312 MAISTRA-2262: Make sure IOR respond to all events
  pilot/pkg/config/kube/ior/route.go
Labels: don't squash, okay to merge, size/L

#302 MAISTRA-2231: Seed MemberRoll listeners with system namespace
  pkg/servicemesh/controller/controller.go
Labels: okay to merge, size/M

#315 MAISTRA-2271: Update xns-informers to fix delete events issue
  go.mod
  go.sum
  vendor/github.com/maistra/xns-informer/pkg/informers/informer.go
  vendor/modules.txt
Labels: okay to merge, size/S

#317 MAISTRA-2274: Workaround client-go issue 91073
  pkg/listwatch/listlenlisterwatcher.go
Labels: okay to merge, size/XS

#318 MAISTRA-2275: Workaround client-go issue 91073
  pkg/listwatch/listlenlisterwatcher.go
Labels: okay to merge, size/XS

#321 MAISTRA-2286: Handle QPS/Burst for galley, mixer and citadel
  galley/pkg/source/kube/client/interfaces.go
  mixer/adapter/kubernetesenv/kubernetesenv.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/controller/client.go
  pilot/pkg/features/pilot.go
  pkg/features/api_client_config.go
  security/cmd/istio_ca/main.go
Labels: okay to merge, size/M

#319 MAISTRA-2280: Delay SMMR Start until caches have synced
  pkg/servicemesh/controller/memberroll/controller.go
Labels: okay to merge, size/L

#320 MAISTRA-2282: Support QPS and Burst settings for mixer
  mixer/adapter/kubernetesenv/kubernetesenv.go
  mixer/pkg/config/crd/init.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/crd/controller/client.go
  pilot/pkg/features/pilot.go
  pkg/features/api_client_config.go
Labels: okay to merge, size/M

#322 MAISTRA-2281: Backport 2.0 SMMR controller changes
  pkg/servicemesh/controller/controller.go
Labels: okay to merge, size/L

#306 MAISTRA-2247 Ensure custom labels in SMCP are applied to istiod pods
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
Labels: okay to merge, size/XS

#326 MAISTRA-2317 Renew expired certs for TestCertOptionsAndRetrieveID
  security/pkg/pki/testdata/ec-root-cert.pem
  security/pkg/pki/testdata/ec-root-key.pem
  security/pkg/pki/testdata/ec-workload-cert.pem
  security/pkg/pki/testdata/ec-workload-key.pem
  security/pkg/pki/util/keycertbundle_test.go
Labels: okay to merge, size/M

#325 MAISTRA-2135 Add unit tests for our CNI binary-prefix work
  cni/cmd/istio-cni/main_test.go
  cni/pkg/install-cni/cmd/root.go
  cni/pkg/install-cni/pkg/config/config.go
  cni/pkg/install-cni/pkg/install/binaries.go
  cni/pkg/install-cni/pkg/install/binaries_test.go
  cni/pkg/install-cni/pkg/install/install.go
  cni/pkg/install-cni/pkg/install/install_test.go
  cni/pkg/install-cni/pkg/install/testdata/istio-cni-prefixed.conf
  cni/pkg/install-cni/pkg/install/testdata/list-no-istio.conflist
Labels: okay to merge, size/L

#316 MAISTRA-1992 and others
  manifests/charts/base/crds/maistra.io_meshfederations.yaml
  manifests/charts/base/crds/maistra.io_servicemeshextensions.yaml
  manifests/charts/base/crds/maistra.io_servicemeshmemberrolls.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  mec/cmd/mec/main.go
  mec/pkg/model/interfaces.go
  mec/pkg/model/types.go
  mec/pkg/pullstrategy/fake/strategy.go
  mec/pkg/pullstrategy/ossm/strategy.go
  mec/pkg/pullstrategy/ossm/strategy_test.go
  mec/pkg/server/httpserver.go
  mec/pkg/server/worker.go
  mec/pkg/server/worker_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/model/push_context.go
  pilot/pkg/model/push_context_test.go
  pkg/servicemesh/apis/servicemesh/v1/register.go
  pkg/servicemesh/apis/servicemesh/v1/servicemeshextension_types.go
  pkg/servicemesh/apis/servicemesh/v1/zz_generated.deepcopy.go
  pkg/servicemesh/client/v1/clientset/versioned/typed/servicemesh/v1/fake/fake_servicemesh_client.go
  pkg/servicemesh/client/v1/clientset/versioned/typed/servicemesh/v1/fake/fake_servicemeshextension.go
  pkg/servicemesh/client/v1/clientset/versioned/typed/servicemesh/v1/generated_expansion.go
  pkg/servicemesh/client/v1/clientset/versioned/typed/servicemesh/v1/servicemesh_client.go
  pkg/servicemesh/client/v1/clientset/versioned/typed/servicemesh/v1/servicemeshextension.go
  pkg/servicemesh/client/v1/informers/externalversions/generic.go
  pkg/servicemesh/client/v1/informers/externalversions/servicemesh/v1/interface.go
  pkg/servicemesh/client/v1/informers/externalversions/servicemesh/v1/servicemeshextension.go
  pkg/servicemesh/client/v1/listers/servicemesh/v1/expansion_generated.go
  pkg/servicemesh/client/v1/listers/servicemesh/v1/servicemeshextension.go
  pkg/servicemesh/controller/extension/controller.go
  pkg/servicemesh/extension/apply_extension.go
  pkg/servicemesh/maistra.mk
  pkg/servicemesh/model/extension.go
Labels: don't squash, okay to merge, size/XXL
