Repository maistra/istio, pull requests merged in 2021-03, with the labels that each got.

#275 MAISTRA-2149: Make IOR robust in multiple replicas
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/route.go
  pilot/pkg/leaderelection/leaderelection.go
Labels: cherrypick/maistra-2.1, okay to merge, size/M

#282 MAISTRA-2149: Make IOR robust in multiple replicas
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/route.go
  pilot/pkg/leaderelection/leaderelection.go
Labels: okay to merge, size/M

#283 MAISTRA-2153: Disable namespace informer if MemberRoll is used
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge, size/XS

#280 MAISTRA-2151: ensure locks are released using defer
  istio.deps
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: okay to merge, size/M

#278 Maistra 2101
  pilot/pkg/proxy/envoy/v2/debug.go
Labels: okay to merge, size/M

#286 MAISTRA-1813: Add unit tests for IOR
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ior/client.go
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/XL

#287 MAISTRA-2165 incorrect lock used in test Reset for tls_ecdh_curves
  pkg/features/tls_ecdh_curves.go
Labels: okay to merge, size/XS

#288 MAISTRA-2166 incorrect lock used in test Reset for tls_ecdh_curves
  pkg/features/tls_ecdh_curves.go
Labels: cherrypick/maistra-2.1, okay to merge, size/XS

#268 OSSM-357 Use the correct port when updating ServiceEntry endpoints
  pilot/pkg/serviceregistry/external/servicediscovery.go
Labels: okay to merge, size/XS

#284 MAISTRA-2051 fixes for maistra install
  cni/cmd/istio-cni/iptables.go
  cni/cmd/istio-cni/kubernetes.go
  cni/cmd/istio-cni/main.go
  cni/cmd/istio-cni/main_test.go
  cni/cmd/istio-cni/redirect.go
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  pilot/pkg/config/kube/ior/ior_test.go
  pkg/kube/client.go
  pkg/kube/inject/inject.go
  pkg/kube/inject/testdata/inject/hello-cncf-networks.yaml.injected
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml.injected
  pkg/kube/inject/testdata/inject/hello-existing-cncf-networks.yaml.injected
  pkg/kube/inject/testdata/inject/hello.yaml.cni.injected
  pkg/kube/inject/webhook.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/cmd/run.go
  tools/istio-iptables/pkg/cmd/run_test.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
Labels: don't squash, okay to merge, size/L

#290 MAISTRA-2175: backport upstream performance PR
  pilot/pkg/model/push_context.go
  pilot/pkg/model/sidecar.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
Labels: okay to merge, size/L

#291 MAISTRA-2197: Push first update when cache is warm
  pkg/servicemesh/controller/memberroll/controller.go
Labels: cherrypick/maistra-2.1, okay to merge, size/M

#294 MAISTRA-2197: Push first update when cache is warm
  pkg/servicemesh/controller/controller.go
Labels: okay to merge, size/M

#295 MAISTRA-2164: Refactor IOR internals
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/XL

#296 MAISTRA-2164: Refactor IOR internals
  Makefile.core.mk
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/L

#298 MAISTRA-2217: backport of istio PR 25733
  pilot/pkg/bootstrap/server.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: okay to merge, size/M

#301 MAISTRA-2223: Include istiod support for affinity and tolerations
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/_affinity.tpl
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
Labels: okay to merge, size/L

#299 MAISTRA-2218: backport of istio PR 25733
  pilot/pkg/bootstrap/server.go
  pilot/pkg/proxy/envoy/v2/ads.go
  pilot/pkg/proxy/envoy/v2/discovery.go
Labels: okay to merge, size/M

#303 MAISTRA-2233: Start xns-informers with empty namespace set
  pkg/kube/client.go
Labels: okay to merge, size/S
