Repository maistra/istio, pull requests merged in 2021-01, with the labels that each got.

#221 MAISTRA-2051 xns-informers for istio types
  go.mod
  go.sum
  pkg/kube/client.go
  pkg/test/kube/mock_client.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/factory.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/generic.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/interface.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1alpha3/destinationrule.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1alpha3/envoyfilter.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1alpha3/gateway.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1alpha3/interface.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1alpha3/serviceentry.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1alpha3/sidecar.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1alpha3/virtualservice.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1alpha3/workloadentry.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1alpha3/workloadgroup.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1beta1/destinationrule.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1beta1/gateway.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1beta1/interface.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1beta1/serviceentry.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1beta1/sidecar.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1beta1/virtualservice.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/networking/v1beta1/workloadentry.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/security/interface.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/security/v1beta1/authorizationpolicy.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/security/v1beta1/interface.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/security/v1beta1/peerauthentication.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/security/v1beta1/requestauthentication.go
  vendor/github.com/maistra/xns-informer/pkg/generated/kube/factory.go
  vendor/github.com/maistra/xns-informer/pkg/generated/kube/generic.go
  vendor/github.com/maistra/xns-informer/pkg/testing/clients.go
  vendor/istio.io/client-go/pkg/apis/networking/v1alpha3/types.gen.go
  vendor/istio.io/client-go/pkg/apis/networking/v1beta1/types.gen.go
  vendor/istio.io/client-go/pkg/apis/security/v1beta1/types.gen.go
  vendor/istio.io/client-go/pkg/informers/externalversions/factory.gen.go
  vendor/istio.io/client-go/pkg/informers/externalversions/networking/interface.gen.go
  vendor/istio.io/client-go/pkg/informers/externalversions/security/interface.gen.go
  vendor/modules.txt
Labels: okay to merge, size/XXL

#227 MAISTRA-2051: Add MemberRollController
  Makefile.core.mk
  pilot/cmd/pilot-discovery/main.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pkg/kube/client.go
  pkg/servicemesh/apis/servicemesh/v1/doc.go
  pkg/servicemesh/apis/servicemesh/v1/register.go
  pkg/servicemesh/apis/servicemesh/v1/servicemesh.go
  pkg/servicemesh/apis/servicemesh/v1/zz_generated.deepcopy.go
  pkg/servicemesh/client/clientset/versioned/clientset.go
  pkg/servicemesh/client/clientset/versioned/doc.go
  pkg/servicemesh/client/clientset/versioned/fake/clientset_generated.go
  pkg/servicemesh/client/clientset/versioned/fake/doc.go
  pkg/servicemesh/client/clientset/versioned/fake/register.go
  pkg/servicemesh/client/clientset/versioned/scheme/doc.go
  pkg/servicemesh/client/clientset/versioned/scheme/register.go
  pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1/doc.go
  pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1/fake/doc.go
  pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1/fake/fake_servicemesh_client.go
  pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1/fake/fake_servicemeshmemberroll.go
  pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1/generated_expansion.go
  pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1/servicemesh_client.go
  pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1/servicemeshmemberroll.go
  pkg/servicemesh/client/informers/externalversions/factory.go
  pkg/servicemesh/client/informers/externalversions/generic.go
  pkg/servicemesh/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/servicemesh/client/informers/externalversions/servicemesh/interface.go
  pkg/servicemesh/client/informers/externalversions/servicemesh/v1/interface.go
  pkg/servicemesh/client/informers/externalversions/servicemesh/v1/servicemeshmemberroll.go
  pkg/servicemesh/client/listers/servicemesh/v1/expansion_generated.go
  pkg/servicemesh/client/listers/servicemesh/v1/servicemeshmemberroll.go
  pkg/servicemesh/controller/controller.go
  pkg/servicemesh/header.go.txt
  pkg/servicemesh/maistra.mk
  pkg/test/kube/mock_client.go
Labels: okay to merge, size/XXL

#226 [MAISTRA-2067] [MAISTRA-1528] Fix bookinfo versions to pick up latest version and CVE fixes
  Makefile.core.mk
  pkg/test/deployment/helm.go
  pkg/test/helm/helm.go
  prow/lib.sh
  samples/bookinfo/platform/consul/bookinfo.yaml
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  tests/istio.mk
  tests/util/helm_utils.go
Labels: okay to merge, size/M

#225 MAISTRA-2060: Point to Red Hat Jira for issues
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: cherrypick/maistra-2.1, okay to merge, size/S

#231 MAISTRA-2060 Point to Red Hat Jira for issues
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: okay to merge, size/S

#233 MAISTRA-2060 Disable other issue types
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/SECURITY.md
Labels: okay to merge, size/M

#230 MAISTRA-2051: Run sidecars with dynamically-determined user IDs
  Makefile.core.mk
  istioctl/cmd/testdata/deployment/hello.yaml.injected
  pkg/kube/inject/inject.go
  pkg/kube/inject/testdata/inject/hello-tproxy.yaml.injected
  pkg/kube/inject/testdata/webhook/TestWebhookInject.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_cron_job.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_nosidecar_rewrite.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_disabled_via_annotation.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_http_probe_rewrite_enabled_via_annotation.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_https_probe_rewrite.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_injectorAnnotations.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_mtls_not_ready.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers_volumes.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers_volumes_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_containers.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_containers_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_containers_volumes.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_volumes.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_volumes_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initcontainers_containers_volumes_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_volumes.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_no_volumes_imagePullSecrets.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_probe_rewrite_timeout_retention.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_replace.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_replace_backwards_compat.patch
  pkg/kube/inject/testdata/webhook/TestWebhookInject_validationOrder.patch
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: okay to merge, size/L

#234 Do not download envoy-centos image
  bin/init.sh
  istio.deps
  pilot/docker/Dockerfile.proxyv2
  pkg/test/framework/components/echo/kube/deployment.go
  prow/lib.sh
Labels: okay to merge, size/M

#237 [MAISTRA-1367][MAISTRA-1528][MAISTRA-1783] Use maistra bookinfo images in bookinfo example
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/httpbin/httpbin.yaml
  samples/httpbin/sample-client/fortio-deploy.yaml
  samples/https/nginx-app.yaml
  samples/sleep/sleep.yaml
Labels: okay to merge, size/M

#241 MAISTRA-2051: Use shared Kubernetes client in galley
  galley/pkg/config/analysis/local/analyze.go
  galley/pkg/config/analysis/local/analyze_test.go
  galley/pkg/config/source/kube/apiserver/options.go
  galley/pkg/config/source/kube/apiserver/source.go
  galley/pkg/config/source/kube/apiserver/source_builtin_test.go
  galley/pkg/config/source/kube/apiserver/source_dynamic_test.go
  galley/pkg/config/source/kube/apiserver/status/controller_test.go
  galley/pkg/config/source/kube/rt/dynamic.go
  galley/pkg/config/source/kube/rt/known.go
  galley/pkg/config/source/kube/rt/provider.go
  galley/pkg/server/components/processing.go
  galley/pkg/server/components/processing_test.go
  istioctl/cmd/analyze.go
  pilot/pkg/bootstrap/configcontroller.go
  tools/bug-report/pkg/content/content.go
Labels: okay to merge, size/L

#251 Make `make docker` work again
  Makefile.core.mk
  bin/init.sh
  istio.deps
Labels: okay to merge, size/XS
