Repository maistra/istio, pull requests merged in 2021-07, with the labels that each got.

#383 MAISTRA-2463: copy seed namespaces when set
  pkg/servicemesh/controller/memberroll/controller.go
  pkg/servicemesh/controller/memberroll/controller_test.go
Labels: okay to merge, size/M

#384 MAISTRA-2464: copy seed namespaces when set
  pkg/servicemesh/controller/controller.go
  pkg/servicemesh/controller/controller_test.go
Labels: okay to merge, size/M

#391 MAISTRA-2437: Push configuration as String
  pkg/servicemesh/extension/apply_extension.go
Labels: okay to merge, size/M

#392 MAISTRA-2425 move spec.security.certificateChain to ConfigMap referen…
  go.mod
  go.sum
  manifests/charts/base/crds/maistra.io_federationstatuses.yaml
  manifests/charts/base/crds/maistra.io_meshfederations.yaml
  manifests/charts/base/crds/maistra.io_serviceexports.yaml
  manifests/charts/base/crds/maistra.io_serviceimports.yaml
  manifests/charts/base/crds/maistra.io_servicemeshextensions.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  pilot/pkg/serviceregistry/federation/controller.go
  pilot/pkg/serviceregistry/federation/routing.go
  pkg/servicemesh/federation/common/const.go
  pkg/servicemesh/federation/common/util.go
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/discovery/controller_test.go
  pkg/servicemesh/federation/discovery/discovery.go
  pkg/servicemesh/federation/example/config-poc/export/configmap.yaml
  pkg/servicemesh/federation/example/config-poc/export/meshfederation.yaml
  pkg/servicemesh/federation/example/config-poc/export/smcp.yaml
  pkg/servicemesh/federation/example/config-poc/import/configmap.yaml
  pkg/servicemesh/federation/example/config-poc/import/meshfederation.yaml
  pkg/servicemesh/federation/example/config-poc/import/smcp.yaml
  pkg/servicemesh/federation/example/config-poc/install.sh
  pkg/servicemesh/federation/server/routing.go
  pkg/servicemesh/federation/server/server.go
  vendor/maistra.io/api/core/v1/meshfederation_types.go
  vendor/maistra.io/api/core/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: okay to merge, size/XL

#390 MAISTRA-2478 Honor enableIngressClassName in ingress status syncer
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingress/status_test.go
Labels: okay to merge, size/XS

#395 Use our proxy \o/
  Makefile.core.mk
  istio.deps
Labels: okay to merge, size/XS

#396 MAISTRA-2495 Remove runAsUser field from bookinfo examples
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: okay to merge, size/S

#397 MAISTRA-2496: Prevent sendEvent from holding the lock
  pkg/listwatch/listinformer.go
  pkg/listwatch/listinformer_test.go
  pkg/listwatch/listwatch.go
Labels: okay to merge, size/L

#399 MAISTRA-2497: Prevent sendEvent from holding the lock
  pkg/listwatch/listinformer.go
  pkg/listwatch/listinformer_test.go
  pkg/listwatch/listwatch.go
Labels: okay to merge, size/L

#400 MAISTRA-2498 Fix flaky integration test TestPassThroughFilterChain
  pkg/test/framework/components/echo/echotest/echotest.go
  pkg/test/framework/components/echo/echotest/run.go
  pkg/test/framework/components/echo/echotest/setup.go
  tests/integration/security/pass_through_filter_chain_test.go
Labels: okay to merge, size/S

#402 MAISTRA-2517 Add sidecar.istio.io/inject annotation to bookinfo examples
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: okay to merge, size/M

#404 MAISTRA-2519 Fix connection to MongoDB in bookinfo ratings-v2
  samples/bookinfo/src/ratings/ratings.js
Labels: okay to merge, size/XS

#403 MAISTRA-2454 Add multi-cluster support to federation example
  pkg/servicemesh/federation/example/config-poc/cleanup.sh
  pkg/servicemesh/federation/example/config-poc/common.sh
  pkg/servicemesh/federation/example/config-poc/export/servicemeshpeer.yaml
  pkg/servicemesh/federation/example/config-poc/export/smcp.yaml
  pkg/servicemesh/federation/example/config-poc/import/servicemeshpeer.yaml
  pkg/servicemesh/federation/example/config-poc/import/smcp.yaml
  pkg/servicemesh/federation/example/config-poc/install.sh
Labels: okay to merge, size/L

#405 MAISTRA-2454 - Enabling Prometheus, Grafana and Kiali for both Meshes…
  pkg/servicemesh/federation/example/config-poc/export/smcp.yaml
  pkg/servicemesh/federation/example/config-poc/import/smcp.yaml
Labels: okay to merge, size/XS

#408 use -f test to not only check they are non-empty but also that they point to valid files
  pkg/servicemesh/federation/example/config-poc/common.sh
Labels: ok-to-test, okay to merge, size/XS

#409 MAISTRA-2534 Reject invalid jwks and add integration test for jwt rules
  pilot/pkg/security/authn/v1beta1/policy_applier.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  tests/integration/security/jwt_test.go
  tests/integration/security/testdata/requestauthn/a-authn.yaml.tmpl
  tests/integration/security/testdata/requestauthn/b-authn-authz.yaml.tmpl
  tests/integration/security/testdata/requestauthn/c-authn.yaml.tmpl
  tests/integration/security/testdata/requestauthn/e-authn.yaml.tmpl
  tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl
Labels: okay to merge, size/M

#410 MAISTRA-2537: Use bookinfo images from quay.io
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: okay to merge, size/M

#412 MAISTRA-2535: Restore proxyEnv support (#378)
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
  manifests/charts/istiod-remote/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/injection-template.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
  operator/cmd/mesh/testdata/manifest-generate/output/sidecar_template.golden.yaml
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/maistra_env_annotations.yaml
  pkg/kube/inject/testdata/inject/maistra_env_annotations.yaml.injected
Labels: okay to merge, size/L

#407 Update maistra/api dependency
  go.mod
  go.sum
  pkg/servicemesh/federation/common/namemapping.go
  vendor/maistra.io/api/federation/v1/exportedserviceset_types.go
  vendor/maistra.io/api/federation/v1/import_export_mapping.go
  vendor/maistra.io/api/federation/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: okay to merge, size/S

#411 MAISTRA-2237 Encrypt service discovery traffic
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/federation.yaml
  pilot/pkg/bootstrap/server.go
  pkg/servicemesh/federation/federation.go
  pkg/servicemesh/federation/server/server.go
  pkg/servicemesh/federation/server/server_test.go
Labels: okay to merge, size/L

#413 Get mesh2 ports from correct resource
  pkg/servicemesh/federation/example/config-poc/install.sh
Labels: ok-to-test, okay to merge, size/XS
