Repository maistra/istio, pull requests merged in 2021-05, with the labels that each got.

#330 MAISTRA-2329: Remove SMMR CRD from this repo
  manifests/charts/base/crds/maistra.io_servicemeshmemberrolls.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
Labels: okay to merge, size/L

#333 MAISTRA-2294 update example VirtualService resources for ratings and …
  pkg/servicemesh/federation/example/config-poc/examples/mongodb-remote-virtualservice.yaml
  pkg/servicemesh/federation/example/config-poc/examples/ratings-split-virtualservice.yaml
  pkg/servicemesh/federation/example/config-poc/install.sh
Labels: okay to merge, size/M

#337 MAISTRA-2346: Add script to update maistra deps
  bin/update_maistra_deps.sh
Labels: okay to merge, size/M

#340 MAISTRA-2355: Change httpbin port to 8000
  samples/httpbin/httpbin-nodeport.yaml
  samples/httpbin/httpbin-vault.yaml
  samples/httpbin/httpbin.yaml
Labels: okay to merge, size/S

#327 MAISTRA-2318 Renew expired certs for TestCertOptionsAndRetrieveID in 2.0
  security/pkg/pki/testdata/ec-root-cert.pem
  security/pkg/pki/testdata/ec-root-key.pem
  security/pkg/pki/testdata/ec-workload-cert.pem
  security/pkg/pki/testdata/ec-workload-key.pem
  security/pkg/pki/util/keycertbundle_test.go
Labels: okay to merge, size/M

#341 OSSM 449: dedupe domains in virtualhosts
  pilot/pkg/networking/core/v1alpha3/httproute.go
  pilot/pkg/networking/core/v1alpha3/httproute_test.go
Labels: okay to merge, size/L

#343 MAISTRA-2371: Handle tombstones when handling events from the namespa…
  pkg/listwatch/listinformer.go
  pkg/listwatch/listinformer_test.go
Labels: okay to merge, size/M

#336 MAISTRA-2295 create CRD for federation ServiceImport
  bin/update_maistra_deps.sh
  go.mod
  go.sum
  manifests/charts/base/crds/maistra.io_serviceexports.yaml
  manifests/charts/base/crds/maistra.io_serviceimports.yaml
  manifests/charts/base/files/gen-istio-cluster.yaml
  manifests/charts/base/templates/crds.yaml
  manifests/charts/base/templates/role.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/serviceregistry/federation/controller.go
  pilot/pkg/serviceregistry/federation/routing.go
  pkg/kube/controller/controller.go
  pkg/servicemesh/federation/common/const.go
  pkg/servicemesh/federation/common/exports.go
  pkg/servicemesh/federation/common/imports.go
  pkg/servicemesh/federation/common/namemapping.go
  pkg/servicemesh/federation/common/util.go
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/discovery/controller_test.go
  pkg/servicemesh/federation/discovery/discovery.go
  pkg/servicemesh/federation/example/config-poc/examples/mongodb-remote-virtualservice.yaml
  pkg/servicemesh/federation/example/config-poc/examples/ratings-split-virtualservice.yaml
  pkg/servicemesh/federation/example/config-poc/import/serviceimports.yaml
  pkg/servicemesh/federation/example/config-poc/install.sh
  pkg/servicemesh/federation/export/exports.go
  pkg/servicemesh/federation/exports/controller.go
  pkg/servicemesh/federation/federation.go
  pkg/servicemesh/federation/imports/controller.go
  pkg/servicemesh/federation/model/model.go
  pkg/servicemesh/federation/server/routing.go
  pkg/servicemesh/federation/server/server.go
  pkg/servicemesh/federation/server/server_test.go
  vendor/maistra.io/api/client/informers/externalversions/core/v1alpha1/interface.go
  vendor/maistra.io/api/client/informers/externalversions/core/v1alpha1/serviceimports.go
  vendor/maistra.io/api/client/informers/externalversions/generic.go
  vendor/maistra.io/api/client/listers/core/v1alpha1/expansion_generated.go
  vendor/maistra.io/api/client/listers/core/v1alpha1/serviceimports.go
  vendor/maistra.io/api/client/versioned/typed/core/v1alpha1/core_client.go
  vendor/maistra.io/api/client/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  vendor/maistra.io/api/client/versioned/typed/core/v1alpha1/fake/fake_serviceimports.go
  vendor/maistra.io/api/client/versioned/typed/core/v1alpha1/generated_expansion.go
  vendor/maistra.io/api/client/versioned/typed/core/v1alpha1/serviceimports.go
  vendor/maistra.io/api/core/v1alpha1/groupversion_info.go
  vendor/maistra.io/api/core/v1alpha1/import_export_mapping.go
  vendor/maistra.io/api/core/v1alpha1/serviceexports_types.go
  vendor/maistra.io/api/core/v1alpha1/serviceimports_types.go
  vendor/maistra.io/api/core/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: okay to merge, size/XXL
