Repository maistra/istio, pull requests merged in 2022-10, with the labels that each got.

#627 OSSM-2049: Fix handling ServiceAccounts in federation controller
  pilot/pkg/serviceregistry/federation/controller.go
Labels: okay to merge, size/XS

#636 OSSM-1206: Make ServiceEntries with duplicated host names reachable
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  releasenotes/notes/serviceentry-ip-auto-allocation.yaml
Labels: okay to merge, size/M

#638 OSSM-2082 CNI installer now creates the net.d directory if necessary
  cni/pkg/install/kubeconfig.go
  cni/pkg/install/kubeconfig_test.go
Labels: okay to merge, size/S

#617 OSSM-2049: Fix handling Endpoints in federation controller
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/common/util.go
Labels: okay to merge, size/M, maistra-2.2

#642 OSSM-2074 Fix issues in the analysis controller
  pilot/pkg/config/kube/crdclient/client.go
  pkg/config/analysis/incluster/controller.go
Labels: okay to merge, size/S

#640 [maistra-2.2] OSSM-1206: Make ServiceEntries with duplicated host names reachable
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  releasenotes/notes/serviceentry-ip-auto-allocation.yaml
Labels: okay to merge, size/M

#643 OSSM-2006 Fix multiNamespaceInformer.HasSynced()
  galley/pkg/config/source/kube/rt/provider.go
  go.mod
  go.sum
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/route.go
  pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
  pkg/kube/client.go
  pkg/servicemesh/controller/controller.go
  pkg/servicemesh/controller/extension/controller.go
  vendor/github.com/maistra/xns-informer/pkg/generated/gatewayapi/factory.go
  vendor/github.com/maistra/xns-informer/pkg/generated/istio/factory.go
  vendor/github.com/maistra/xns-informer/pkg/generated/kube/factory.go
  vendor/github.com/maistra/xns-informer/pkg/informers/dynamic.go
  vendor/github.com/maistra/xns-informer/pkg/informers/informer.go
  vendor/github.com/maistra/xns-informer/pkg/informers/metadata.go
  vendor/github.com/maistra/xns-informer/pkg/informers/namespace_set.go
  vendor/maistra.io/api/client/xnsinformer/factory.go
  vendor/modules.txt
Labels: okay to merge, size/L, maistra-2.2

#628 OSSM-2049: Fix handling Endpoints and ServiceAccounts in federation controller
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/common/util.go
Labels: okay to merge, size/M, maistra-2.1

#641 [maistra-2.1] OSSM-1206: Make ServiceEntries with duplicated host names reachable
  pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
  pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
  releasenotes/notes/serviceentry-ip-auto-allocation.yaml
Labels: okay to merge, size/M

#645 OSSM-2109 Fix flaky IOR unit test
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/XS, cherrypick/maistra-2.2, cherrypick/maistra-2.3

#646 Set default CONTAINER_CLI to docker
  maistra/maistra.mk
Labels: okay to merge, size/XS

#651 OSSM-2107 Update bookinfo images for 2.3
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: okay to merge, size/M

#653 OSSM-1093 Shorten exported resource name
  pilot/pkg/serviceregistry/federation/routing.go
  pkg/servicemesh/federation/common/util.go
  pkg/servicemesh/federation/common/util_test.go
  pkg/servicemesh/federation/server/routing.go
Labels: okay to merge, size/L, cherrypick/maistra-2.2

#656 OSSM-1093 Shorten exported/imported resource name (cherry-pick)
  pilot/pkg/serviceregistry/federation/routing.go
  pkg/servicemesh/federation/common/util.go
  pkg/servicemesh/federation/common/util_test.go
  pkg/servicemesh/federation/server/routing.go
Labels: okay to merge, size/L

#659 Re-add injection label on some samples
  samples/httpbin/httpbin-nodeport.yaml
  samples/httpbin/httpbin.yaml
  samples/httpbin/sample-client/fortio-deploy.yaml
  samples/sleep/sleep.yaml
Labels: okay to merge, size/XS

#657 OSSM-755: Fix TLS certificates used in security tests
  pkg/istio-agent/agent_test.go
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/testdata/certs/default/cert-chain.pem
  tests/testdata/certs/default/key.pem
  tests/testdata/certs/default/root-cert.pem
  tests/testdata/certs/dns/cert-chain.pem
  tests/testdata/certs/dns/key.pem
  tests/testdata/certs/dns/root-cert.pem
  tests/testdata/certs/generate.sh
  tests/testdata/certs/mountedcerts-client/cert-chain.pem
  tests/testdata/certs/mountedcerts-client/key.pem
  tests/testdata/certs/mountedcerts-client/root-cert.pem
  tests/testdata/certs/mountedcerts-server/cert-chain.pem
  tests/testdata/certs/mountedcerts-server/key.pem
  tests/testdata/certs/mountedcerts-server/root-cert.pem
  tests/testdata/certs/pilot/ca-cert.pem
  tests/testdata/certs/pilot/ca-key.pem
  tests/testdata/certs/pilot/cert-chain.pem
  tests/testdata/certs/pilot/key.pem
  tests/testdata/certs/pilot/root-cert.pem
Labels: okay to merge, size/XL

#663 OSSM-2147 Initialize analysis client with the actual revision
  pilot/pkg/bootstrap/configcontroller.go
  pkg/config/analysis/incluster/controller.go
Labels: okay to merge, size/XS

#661 OSSM-755: Fix TLS certificates used in security tests
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
  tests/testdata/certs/default/cert-chain.pem
  tests/testdata/certs/default/key.pem
  tests/testdata/certs/default/root-cert.pem
  tests/testdata/certs/dns/cert-chain.pem
  tests/testdata/certs/dns/key.pem
  tests/testdata/certs/dns/root-cert.pem
  tests/testdata/certs/generate.sh
  tests/testdata/certs/mountedcerts-client/cert-chain.pem
  tests/testdata/certs/mountedcerts-client/key.pem
  tests/testdata/certs/mountedcerts-client/root-cert.pem
  tests/testdata/certs/mountedcerts-server/cert-chain.pem
  tests/testdata/certs/mountedcerts-server/key.pem
  tests/testdata/certs/mountedcerts-server/root-cert.pem
  tests/testdata/certs/pilot/ca-cert.pem
  tests/testdata/certs/pilot/ca-key.pem
  tests/testdata/certs/pilot/cert-chain.pem
  tests/testdata/certs/pilot/key.pem
  tests/testdata/certs/pilot/root-cert.pem
Labels: okay to merge, size/XL, maistra-2.2

#664 Add delete configmap privilege to fix distribution report cleanup
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/role.yaml
  manifests/charts/istiod-remote/templates/role.yaml
Labels: okay to merge, size/S

#662 OSSM-755: Fix TLS certificates used in security tests
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
  tests/testdata/certs/default/cert-chain.pem
  tests/testdata/certs/default/key.pem
  tests/testdata/certs/default/root-cert.pem
  tests/testdata/certs/dns/cert-chain.pem
  tests/testdata/certs/dns/key.pem
  tests/testdata/certs/dns/root-cert.pem
  tests/testdata/certs/generate.sh
  tests/testdata/certs/mountedcerts-client/cert-chain.pem
  tests/testdata/certs/mountedcerts-client/key.pem
  tests/testdata/certs/mountedcerts-client/root-cert.pem
  tests/testdata/certs/mountedcerts-server/cert-chain.pem
  tests/testdata/certs/mountedcerts-server/key.pem
  tests/testdata/certs/mountedcerts-server/root-cert.pem
  tests/testdata/certs/pilot/ca-cert.pem
  tests/testdata/certs/pilot/ca-key.pem
  tests/testdata/certs/pilot/cert-chain.pem
  tests/testdata/certs/pilot/key.pem
  tests/testdata/certs/pilot/root-cert.pem
Labels: size/XL, maistra-2.1

#665 OSSM-2179: changes the restriction about the number of layers in a WASM plugin.
  pkg/wasm/imagefetcher.go
  pkg/wasm/imagefetcher_test.go
  releasenotes/notes/wasm-multilayer.yaml
Labels: okay to merge, size/L

#666 OSSM-2193 Refactor and fix flaky TestStatusManager
  pkg/servicemesh/federation/status/handler.go
  pkg/servicemesh/federation/status/manager_test.go
Labels: okay to merge, don't squash, size/XL, cherrypick/maistra-2.2
