Repository maistra/istio, pull requests merged in 2022-11, with the labels that each got.

#667 OSSM-2193 cherry-picked to 2.2
  pkg/servicemesh/federation/status/handler.go
  pkg/servicemesh/federation/status/manager_test.go
Labels: okay to merge, don't squash, size/XL

#684 fix(xns-informer): only sync nsInformer when not nil
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
Labels: okay to merge, size/XS

#680 OSSM-2256: Add IOR
  go.mod
  go.sum
  licenses/github.com/openshift/client-go/LICENSE
  licenses/github.com/stretchr/testify/LICENSE
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ior/client.go
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
  pilot/pkg/features/pilot.go
  pilot/pkg/leaderelection/leaderelection.go
  pkg/kube/client.go
  pkg/kube/mock_client.go
  tests/integration/servicemesh/main_test.go
  tests/integration/servicemesh/maistra/maistra.go
  tests/integration/servicemesh/router/router.go
  tests/integration/servicemesh/router/testdata/route_crd.yaml
  tests/integration/servicemesh/router/testdata/router.yaml
  tests/integration/servicemesh/router/testdata/router_rbac.yaml
  tests/integration/servicemesh/smmr_test.go
Labels: okay to merge, size/XXL

#685 Fix test arg from previous merge
  tests/integration/servicemesh/maistra/maistra.go
Labels: okay to merge, size/XS

#687 Sync with 1.16
  common/.commonfiles.sha
  common/config/.golangci.yml
  go.mod
  go.sum
  istio.deps
  manifests/addons/gen.sh
  manifests/charts/istio-operator/files/gen-operator.yaml
  manifests/charts/istio-operator/templates/clusterrole.yaml
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/prune_test.go
  operator/pkg/helmreconciler/testdata/iop-test-gw-1.yaml
  operator/pkg/helmreconciler/testdata/iop-test-gw-2.yaml
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/sidecarinjector.go
  pilot/pkg/model/push_context.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/serviceentry/conversion_test.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/h2c/wrapper.go
  pkg/hbone/server.go
  pkg/istio-agent/xds_proxy.go
  pkg/kube/client.go
  pkg/test/echo/server/endpoint/http.go
  pkg/wasm/httpfetcher.go
  pkg/wasm/imagefetcher.go
  pkg/webhooks/util/util.go
  pkg/webhooks/validation/controller/controller.go
  pkg/webhooks/webhookpatch.go
  pkg/webhooks/webhookpatch_test.go
  releasenotes/notes/40578.yaml
  releasenotes/notes/41161.yaml
  releasenotes/notes/kiali-update-v1.59.1.yaml
  releasenotes/notes/scope-webhook-cert-patching.yaml
  samples/addons/kiali.yaml
  samples/bookinfo/gateway-api/route-all-v1.yaml
  samples/bookinfo/gateway-api/route-reviews-50-v3.yaml
  samples/bookinfo/gateway-api/route-reviews-v1.yaml
  samples/bookinfo/gateway-api/route-reviews-v3.yaml
  samples/bookinfo/platform/kube/bookinfo-versions.yaml
Labels: okay to merge, size/XL, merge strategy

#679 [no-cluster-rbac] OSSM-2255: Preliminary support for Gateway API
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
  pkg/kube/multicluster/secretcontroller.go
  tests/integration/servicemesh/gateway/gateway_test.go
  tests/integration/servicemesh/main_test.go
  tests/integration/servicemesh/maistra/maistra.go
  tests/integration/servicemesh/maistra/testdata/clusterrole.yaml
  tests/integration/servicemesh/maistra/testdata/role.yaml
  tests/integration/servicemesh/smmr_test.go
Labels: okay to merge, size/XL

#693 [cleanup] OSSM-2295 Remove remnants of ServiceMeshExtension support
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istiod-remote/templates/clusterrole.yaml
Labels: okay to merge, size/XS

#694 [build] OSSM-2297 Improve Maistra container images build
  Makefile.core.mk
  maistra/Dockerfile.istio-cni
  maistra/Dockerfile.pilot
  maistra/Dockerfile.proxyv2
  maistra/docker.yaml
  maistra/maistra.mk
  maistra/scripts/post-build.sh
  maistra/scripts/pre-build.sh
Labels: okay to merge, size/L

#689 [proxy-uid] OSSM-2292: Run sidecars with dynamically-determined user IDs
  Makefile.core.mk
  istioctl/cmd/testdata/deployment/hello-with-proxyconfig-anno.yaml.injected
  istioctl/cmd/testdata/deployment/hello.yaml.injected
  istioctl/cmd/testdata/deployment/hello.yaml.iop.injected
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/grpc-agent.yaml.injected
  pkg/kube/inject/testdata/inject/hello-tproxy.yaml.injected
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: okay to merge, size/L

#691 [samples] Update bookinfo images for 2.4
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/extauthz/local-ext-authz.yaml
  samples/grpc-echo/grpc-echo.yaml
  samples/httpbin/httpbin-nodeport.yaml
  samples/httpbin/httpbin-vault.yaml
  samples/httpbin/httpbin.yaml
Labels: okay to merge, size/L

#688 [cni] MAISTRA-2291 Support deployment of multiple plugin versions in Istio CNI
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/install/binaries.go
  cni/pkg/install/binaries_test.go
  cni/pkg/install/cniconfig.go
  cni/pkg/install/install.go
  cni/pkg/install/install_test.go
  cni/pkg/install/kubeconfig.go
  cni/pkg/install/kubeconfig_test.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/kubernetes.go
  cni/pkg/plugin/redirect.go
  cni/pkg/util/util.go
Labels: okay to merge, size/L

#692 [istiod] OSSM-2294 Add --logKubernetesApiRequests option to istiod
  pilot/cmd/pilot-discovery/app/cmd.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/util.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge, size/M

#696 [tls] MAISTRA-2051: Add extended TLS options
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  operator/pkg/validate/validate_test.go
  operator/pkg/validate/validate_values_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/server_test.go
  pilot/pkg/bootstrap/webhook.go
  pilot/pkg/networking/core/v1alpha3/gateway.go
  pilot/pkg/networking/core/v1alpha3/gateway_test.go
  pilot/pkg/networking/core/v1alpha3/listener.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
  pkg/features/tls_cipher_suites.go
  pkg/features/tls_ecdh_curves.go
  pkg/features/tls_protocol_version.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.34.values.gen.yaml
  pkg/kube/inject/testdata/inputs/default.values.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.values.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.values.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.values.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.values.gen.yaml
Labels: okay to merge, size/XL
