Repository maistra/istio, pull requests merged in 2022-06, with the labels that each got.

#524 OSSM-993 Deprecate ServiceMeshExtension
  pkg/webhooks/validation/server/server.go
  pkg/webhooks/validation/server/server_test.go
Labels: okay to merge, size/M

#530 [misc] Integration test fixes
  common/scripts/kind_provisioner.sh
  tests/integration/operator/main_test.go
  tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go
  tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
Labels: okay to merge, size/S

#516 OSSM-1442: IOR: Ignore UPDATE events if resourceVersions are the same
  pilot/pkg/config/kube/ior/client.go
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/L

#529 [misc] MAISTRA-2060 Point to Red Hat Jira for issues and disable other issue types
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/SECURITY.md
  README.md
Labels: okay to merge, size/M

#541 [proxy-uid] [MAISTRA-551] Run sidecars with dynamically-determined user IDs (#230)
  Makefile.core.mk
  istioctl/cmd/testdata/deployment/hello.yaml.injected
  istioctl/cmd/testdata/deployment/hello.yaml.iop.injected
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/grpc-agent.yaml.injected
  pkg/kube/inject/testdata/inject/hello-tproxy.yaml.injected
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: okay to merge, size/L, ok-to-test

#545 [no-cluster-rbac] MAISTRA-2051: Allow istiod to run without Node access (#255)
  pilot/cmd/pilot-discovery/app/cmd.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingress/status_test.go
  pilot/pkg/config/kube/ingressv1/status.go
  pilot/pkg/config/kube/ingressv1/status_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge, size/M

#546 [no-cluster-rbac] MAISTRA-1895: Add option to enable/disable CRD scan (#260)
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/crdclient/client_test.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pkg/config/analysis/incluster/controller.go
  pkg/config/analysis/local/istiod_analyze.go
Labels: okay to merge, size/M

#547 [no-cluster-rbac] MAISTRA-1897: Allow disabling IngressClass support (#263)
  pilot/cmd/pilot-discovery/app/cmd.go
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ingress/controller.go
  pilot/pkg/config/kube/ingress/status.go
  pilot/pkg/config/kube/ingress/status_test.go
  pilot/pkg/config/kube/ingressv1/status.go
  pilot/pkg/config/kube/ingressv1/status_test.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge, size/M

#548 ([no-cluster-rbac] OSSM-1420: Ensure istiod can run with no cluster-scoped privileges (#513)
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/ingressv1/controller.go
  pilot/pkg/credentials/kube/secrets.go
  pilot/pkg/leaderelection/leaderelection.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
Labels: okay to merge, size/L
