Repository maistra/istio, pull requests merged in 2022-04, with the labels that each got.

#489 OSSM-1254: Use maistra proxy
  Makefile.core.mk
  istio.deps
  pilot/docker/Dockerfile.proxyv2
  pilot/docker/Dockerfile.proxyv2.maistra
  tests/integration/tests.mk
Labels: okay to merge, size/M

#505 Update bookinfo deployments to 2.2 images
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: okay to merge, size/M

#510 OSSM-1430: CNI: Watch for modified files with a prefix
  cni/pkg/install/cniconfig.go
  cni/pkg/install/install.go
  cni/pkg/util/util.go
Labels: okay to merge, size/S

#512 OSSM-1252 Fix federation status updates
  pkg/servicemesh/federation/status/handler.go
  pkg/servicemesh/federation/status/manager.go
  pkg/servicemesh/federation/status/manager_test.go
Labels: okay to merge, size/L
