Repository maistra/istio, pull requests merged in 2022-12, with the labels that each got.

#701 OSSM-2324 Ensure ProxyUID and ProxyGID are never nil
  pkg/kube/inject/webhook.go
Labels: okay to merge, size/M, don't squash, cherrypick/maistra-2.2, cherrypick/maistra-2.4

#697 OSSM-2074 Fix issues in the analysis controller (#642)
  pilot/pkg/config/kube/crdclient/client.go
  pkg/config/analysis/incluster/controller.go
  tests/integration/servicemesh/gateway/gateway_test.go
  tests/integration/servicemesh/main_test.go
Labels: okay to merge, size/M

#707 OSSM-2338: Remove env ISTIO_META_ROUTER_MODE from federation test
  tests/integration/servicemesh/federation/federation.go
Labels: okay to merge, size/XS, maistra-2.2

#637 OSSM-2000 Re-enable Wasm tests
  tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_filter_test.go
Labels: okay to merge, size/XS

#712 OSSM-2379 [authz] Support for authz regex matching on request head…
  pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-in.yaml
  pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml
  pilot/pkg/security/authz/matcher/header.go
  pilot/pkg/security/authz/model/generator.go
  pilot/pkg/security/authz/model/generator_test.go
  pilot/pkg/security/authz/model/model.go
  pkg/config/security/security.go
  pkg/config/security/security_test.go
Labels: okay to merge, size/L

#713 OSSM-2378: Use Maistra proxy CentOS Stream 8 img
  pilot/docker/Dockerfile.proxyv2
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_stream_8
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/deployment.go
  prow/integ-suite-kind.sh
  prow/lib.sh
  tests/integration/security/sds_ingress/quic/ingress_test.go
  tools/docker.yaml
Labels: okay to merge, size/L

#714 Fix the CRD lookup
  pilot/pkg/config/kube/crdclient/client.go
Labels: okay to merge, size/XS

#711 OSSM-2375 Log the list of member namespaces on every change
  pkg/servicemesh/controller/controller.go
Labels: okay to merge, size/S
