Repository maistra/istio, pull requests merged in 2022-07, with the labels that each got.

#556 [ior] MAISTRA-1400 Add IOR to Pilot
  go.mod
  go.sum
  licenses/github.com/openshift/client-go/LICENSE
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ior/client.go
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
  pilot/pkg/features/pilot.go
  pilot/pkg/leaderelection/leaderelection.go
  pkg/kube/client.go
  tests/integration/servicemesh/main_test.go
  tests/integration/servicemesh/maistra/maistra.go
  tests/integration/servicemesh/router/router.go
  tests/integration/servicemesh/router/testdata/route_crd.yaml
  tests/integration/servicemesh/router/testdata/router.yaml
  tests/integration/servicemesh/router/testdata/router_rbac.yaml
  tests/integration/servicemesh/smmr_test.go
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/legacy.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/LICENSE
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route_client.go
  vendor/modules.txt
Labels: okay to merge, size/XXL

#551 OSSM-1650 Make sure initialSync and event loop behave the same
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/L

#534 OSSM-742 Improve Maistra container images build
  Makefile.core.mk
  maistra.mk
  maistra/Dockerfile.istio-cni
  maistra/Dockerfile.pilot
  maistra/Dockerfile.proxyv2
  maistra/maistra.mk
Labels: okay to merge, size/L

#555 OSSM-1325 prevent crash when serializing services in registryz
  pilot/pkg/xds/debug.go
Labels: okay to merge, size/S

#561 OSSM-1211 Fix federation locality failover issues
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/federation/controller.go
  pilot/pkg/serviceregistry/federation/controller_test.go
Labels: okay to merge, size/L, cherrypick/maistra-2.3

#554 OSSM-1325 lock service before json serialize in registryz
  pilot/pkg/xds/debug.go
Labels: okay to merge, size/XS

#567 OSSM-1650: cherry-pick to maistra
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/L, don't squash

#566 OSSM-1724 Update to 1.12.9
  Makefile.core.mk
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  istioctl/cmd/google.go
  istioctl/cmd/kubeinject.go
  istioctl/pkg/clioptions/central.go
  istioctl/pkg/multixds/gather.go
  istioctl/pkg/multixds/google.go
  istioctl/pkg/xds/client.go
  istioctl/pkg/xds/google.go
  pilot/pkg/controller/workloadentry/workloadentry_controller.go
  pilot/pkg/model/context.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/networkfilter.go
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
  pilot/pkg/networking/core/v1alpha3/route/route_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/serviceregistry/aggregate/controller.go
  pilot/pkg/serviceregistry/aggregate/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
  pilot/pkg/serviceregistry/memory/discovery.go
  pkg/bootstrap/config.go
  pkg/bootstrap/config_test.go
  pkg/istio-agent/agent.go
  pkg/istio-agent/xds_proxy.go
  pkg/istio-agent/xds_proxy_delta.go
  pkg/kube/multicluster/secretcontroller.go
  releasenotes/notes/38754.yaml
  releasenotes/notes/39039.yaml
  releasenotes/notes/39188.yaml
  releasenotes/notes/39201.yaml
  releasenotes/notes/39366.yaml
  tests/integration/pilot/multicluster_test.go
  vendor/istio.io/pkg/log/config.go
  vendor/modules.txt
Labels: okay to merge, size/XL, merge strategy

#522 OSSM-1529 Improve federation example script
  pkg/servicemesh/federation/example/config-poc/README.md
  pkg/servicemesh/federation/example/config-poc/README.txt
  pkg/servicemesh/federation/example/config-poc/install.sh
Labels: okay to merge, size/L

#571 OSSM-1105: Support namespace portion in gateway hostnames
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/M, don't squash
