Repository maistra/istio, pull requests merged in 2022-09, with the labels that each got.

#602 Revert removal of multi-arch node selector in gateways
  istioctl/cmd/remove-from-mesh_test.go
  manifests/charts/gateways/istio-egress/templates/_affinity.tpl
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/templates/_affinity.tpl
  manifests/charts/gateways/istio-ingress/values.yaml
  releasenotes/notes/delete-archs-helm-templates.yaml
Labels: okay to merge, size/M

#581 OSSM-1871 Fix API group in ownerReference
  pilot/pkg/status/reporter.go
Labels: okay to merge, size/XS, cherrypick/maistra-2.3

#609 Use Maistra proxy based on CentOS Stream 8 in integration tests
  Makefile.core.mk
  istio.deps
  pilot/docker/Dockerfile.proxyv2
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_stream_8
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/deployment.go
  prow/integ-suite-kind.sh
  prow/lib.sh
  tests/integration/security/egress_gateway_origination_test.go
  tests/integration/security/file_mounted_certs/p2p_mtls_test.go
  tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
  tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
  tests/integration/security/sds_ingress/quic/ingress_test.go
  tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_filter_test.go
  tools/docker.yaml
Labels: okay to merge, size/L

#614 OSSM-1962: Use EndpointSlices instead of Endpoints in federation controller
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/common/util.go
  tests/integration/servicemesh/federation/federation.go
Labels: okay to merge, size/M

#615 OSSM-1847 ensure ProxyUID and ProxyGID are initialized when using gat…
  pkg/kube/inject/webhook.go
Labels: okay to merge, size/M

#611 OSSM-1938: Run tests on OCP and Change httpbin port and grpc echo uid
  samples/extauthz/local-ext-authz.yaml
  samples/grpc-echo/grpc-echo.yaml
Labels: okay to merge, size/S, cherrypick/maistra-2.2

#630 OSSM-1188 Remove remnants of ServiceMeshExtension support
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  manifests/charts/istiod-remote/templates/clusterrole.yaml
  pkg/servicemesh/model/extension.go
Labels: okay to merge, size/M

#625 OSSM-2041 Add --logKubernetesApiRequests option to istiod
  pilot/cmd/pilot-discovery/app/cmd.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/bootstrap/util.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
Labels: okay to merge, size/M

#631 OSSM-1301 Wait for Route resource type to become available on ior startup
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
Labels: okay to merge, size/S
