Repository maistra/istio, pull requests merged in 2022-03, with the labels that each got.

#467 OSSM-1074 Fix rendering of injectedAnnotations in Helm charts
  manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
  manifests/charts/istiod-remote/templates/istiod-injector-configmap.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
  operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/templates/istiod-injector-configmap.yaml
Labels: okay to merge, size/XS

#471 Harden validation of untrusted inputs
  pilot/pkg/model/context.go
  pilot/pkg/model/context_test.go
  security/pkg/server/ca/authenticate/oidc.go
  security/pkg/util/jwtutil.go
  security/pkg/util/jwtutil_test.go
  tests/fuzz/testdata/FuzzBNMUnmarshalJSON/4811475191988224
  tests/fuzz/testdata/FuzzJwtUtil/5085913745588224
Labels: okay to merge, size/M

#473 OSSM-1074 Fix rendering of injectedAnnotations in Helm charts
  manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
  manifests/charts/istiod-remote/templates/istiod-injector-configmap.yaml
Labels: okay to merge, size/XS

#474 Add routeConfig property to istio-ingress helm values
  manifests/charts/gateways/istio-ingress/values.yaml
Labels: okay to merge, size/XS

#477 OSSM-1150 Fix flaky TestStatusManager unit test
  pkg/servicemesh/federation/status/manager_test.go
Labels: okay to merge, size/L

#480 [federation] OSSM-1128 Fix federation
  pilot/pkg/bootstrap/server.go
  pilot/pkg/security/trustdomain/bundle.go
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/federation.go
  security/pkg/nodeagent/cache/secretcache.go
  tests/integration/servicemesh/federation/federation_test.go
Labels: okay to merge, size/L

#479 OSSM-1185 Make sure to generate valid ImageStreamImport names
  mec/pkg/pullstrategy/ossm/strategy.go
  mec/pkg/pullstrategy/ossm/strategy_test.go
Labels: okay to merge, size/M, ok-to-test

#483 pilot: limit reads from untrusted inputs (#37804)
  pkg/kube/inject/webhook.go
  pkg/kube/util.go
  pkg/webhooks/validation/server/server.go
Labels: okay to merge, size/M, don't squash
