Repository maistra/istio, pull requests merged in 2022-05, with the labels that each got.

#515 OSSM-1445: Upgrade to Istio 1.12.7
  Makefile.core.mk
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/install/install.go
  cni/pkg/install/install_test.go
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  docker/Dockerfile.distroless
  go.mod
  go.sum
  istio.deps
  operator/cmd/mesh/upgrade.go
  operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  operator/pkg/helmreconciler/prune.go
  operator/pkg/helmreconciler/reconciler.go
  pilot/pkg/bootstrap/mesh.go
  pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/metadata.gen.go
  pkg/config/schema/metadata.yaml
  prow/release-commit.sh
  releasenotes/notes/35657.yaml
  releasenotes/notes/38158.yaml
  releasenotes/notes/38496.yaml
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: okay to merge, size/L, merge strategy

#513 OSSM-1420 Ensure istiod can run with no cluster-scoped privileges
  pilot/pkg/config/kube/crdclient/client.go
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/credentials/kube/secrets.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
Labels: okay to merge, size/L

#518 Fix the Jira link
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: okay to merge, size/M
