Repository maistra/istio, pull requests merged in 2023-08, with the labels that each got.

#829 OSSM-4627 Add option to disable the GatewayClass controller
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/features/pilot.go
Labels: okay to merge, size/S

#834 OSSM-4627 Add option to disable the GatewayClass controller
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/features/pilot.go
Labels: okay to merge, size/S

#832 [maistra-2.3] OSSM-4056: Backport setting `istio.alpn_override: "false"` for SIMPLE and MUTUAL TLS
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  releasenotes/notes/40680.yaml
Labels: okay to merge, size/L

#831 [maistra-2.4] OSSM-4056: Backport setting `istio.alpn_override: "false"` for SIMPLE and MUTUAL TLS
  pilot/pkg/networking/core/v1alpha3/cluster_builder.go
  pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
  releasenotes/notes/40680.yaml
Labels: okay to merge, size/L

#838 Fix bookinfo
  samples/bookinfo/src/ratings/Dockerfile
Labels: okay to merge, size/XS

#841 Refactor federation tests
  tests/integration/servicemesh/federation/discovery/discovery_test.go
  tests/integration/servicemesh/federation/federation.go
  tests/integration/servicemesh/federation/federation_test.go
  tests/integration/servicemesh/federation/ha/ha_test.go
  tests/integration/servicemesh/federation/testdata/exported-service-set.tmpl.yaml
  tests/integration/servicemesh/federation/testdata/imported-service-set.tmpl.yaml
  tests/integration/servicemesh/federation/testdata/service-mesh-peer.tmpl.yaml
  tests/integration/servicemesh/maistra/apps.go
Labels: okay to merge, size/XL
