Repository maistra/istio, pull requests merged in 2023-04, with the labels that each got.

#774 Fix integration tests
  common/.commonfiles.sha
  common/scripts/metallb.yaml
  tests/integration/servicemesh/gateway-api/common/gateway_tests.go
  tests/integration/servicemesh/gateway-api/v1alpha2/gateway_test.go
  tests/integration/servicemesh/gateway-api/v1beta1/gateway_test.go
  tests/integration/servicemesh/maistra/maistra.go
Labels: okay to merge, size/XXL

#772 OSSM-2382 Fix istio-cni issue on RHEL9 (#762)
  cni/pkg/plugin/iptables.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/plugin_dryrun_test.go
  releasenotes/notes/43945.yaml
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: okay to merge, size/L

#776 [maistra-2.2] Automator: update common-files@release-1.16 in istio/istio@release-1.16 (#43969)
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: okay to merge, size/L

#778 OSSM-3703: Fix AUTO_RELOAD_PLUGIN_CERTS in multi-tenant mode
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
Labels: okay to merge, size/S

#775 OSSM-3599 Federation egress-gateway gets wrong network gateway endpoints
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/model/model.go
  pkg/servicemesh/federation/server/server.go
  pkg/servicemesh/federation/server/server_test.go
Labels: okay to merge, size/L, cherrypick/maistra-2.2, cherrypick/maistra-2.3

#781 OSSM-3599 Federation egress-gateway gets wrong network gateway endpoints (cherry-pick)
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/model/model.go
  pkg/servicemesh/federation/server/server.go
  pkg/servicemesh/federation/server/server_test.go
Labels: okay to merge, size/L

#783 Change base image of extauthz to redhat/ubi8-micro to support ppc64le and s390x
  samples/extauthz/docker/Dockerfile
Labels: okay to merge, size/XS

#786 OSSM-3784 Fix ownerReference in k8s Gateway Deployment & Service
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/templates/service.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
Labels: okay to merge, size/S

#784 OSSM-3732: Add workaround script for Prow postcommit jobs
  maistra/scripts/run-test-infra-script.sh
Labels: okay to merge, size/M

#788 Restore the istio_version container variable
  maistra/Dockerfile.proxyv2
  maistra/maistra.mk
Labels: okay to merge, size/S

#789 OSSM-3732: Add a helper script to run postsubmit jobs
  maistra/scripts/run-test-infra-script.sh
Labels: okay to merge, size/M

#779 Manual merge of upstream (release-1.16) into maistra-2.4
  pilot/pkg/config/kube/gateway/deploymentcontroller.go
  pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
  pilot/pkg/config/kube/gateway/templates/deployment.yaml
  pilot/pkg/config/kube/gateway/templates/service.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
  pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
  pkg/test/util/assert/assert.go
  releasenotes/notes/gateway-futureproof.yaml
  tests/integration/servicemesh/maistra/testdata/clusterrole.yaml
Labels: okay to merge, size/L
