Repository maistra/istio, pull requests merged in 2023-03, with the labels that each got.

#757 OSSM-2364 remove podman and util-linux from pilot image
  maistra/Dockerfile.pilot
Labels: okay to merge, size/XS

#758 Federation example fixes
  samples/federation/base/export/smcp.yaml
  samples/federation/base/import/smcp.yaml
  samples/federation/base/install.sh
Labels: okay to merge, size/S

#747 OSSM-1689 Simplify IOR
  go.mod
  go.sum
  licenses/github.com/stretchr/testify/LICENSE
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ior/controller.go
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/config/kube/ior/route.go
  pkg/kube/client.go
  pkg/kube/mock_client.go
  tests/integration/servicemesh/maistra/maistra.go
  tests/integration/servicemesh/smmr_test.go
Labels: okay to merge, size/XXL, maistra-2.4

#762 OSSM-2382 Fix istio-cni issue on RHEL9
  cni/pkg/plugin/iptables.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/plugin_dryrun_test.go
  releasenotes/notes/43945.yaml
  tools/istio-clean-iptables/pkg/cmd/cleanup.go
  tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
  tools/istio-iptables/pkg/capture/run.go
  tools/istio-iptables/pkg/capture/run_linux.go
  tools/istio-iptables/pkg/cmd/root.go
  tools/istio-iptables/pkg/config/config.go
  tools/istio-iptables/pkg/constants/constants.go
  tools/istio-iptables/pkg/dependencies/implementation.go
  tools/istio-iptables/pkg/dependencies/implementation_linux.go
  tools/istio-iptables/pkg/dependencies/implementation_unspecified.go
  tools/istio-iptables/pkg/dependencies/interface.go
  tools/istio-iptables/pkg/dependencies/stub.go
Labels: okay to merge, size/L
