Repository maistra/istio, pull requests merged in 2023-01, with the labels that each got.

#718 OSSM-2376: Move kube controller to the federation package
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/exports/controller.go
  pkg/servicemesh/federation/imports/controller.go
  pkg/servicemesh/federation/kube/controller.go
Labels: okay to merge, size/XS

#717 OSSM-2376: Don't start federation controllers until informers have synced
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/common/resources.go
  pkg/servicemesh/federation/common/util.go
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/discovery/controller_test.go
  pkg/servicemesh/federation/exports/controller.go
  pkg/servicemesh/federation/federation.go
  pkg/servicemesh/federation/imports/controller.go
  pkg/servicemesh/federation/kube/controller.go
  pkg/servicemesh/federation/status/handler.go
Labels: okay to merge, size/L

#719 OSSM-2376: Don't start federation controllers until informers have synced (#717)
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/common/resources.go
  pkg/servicemesh/federation/common/util.go
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/discovery/controller_test.go
  pkg/servicemesh/federation/exports/controller.go
  pkg/servicemesh/federation/federation.go
  pkg/servicemesh/federation/imports/controller.go
  pkg/servicemesh/federation/kube/controller.go
  pkg/servicemesh/federation/status/handler.go
Labels: okay to merge, size/L, maistra-2.2

#720 OSSM-2376: Don't start federation controllers until informers have synced (#717)
  pilot/pkg/serviceregistry/federation/controller.go
  pkg/servicemesh/federation/common/resources.go
  pkg/servicemesh/federation/common/util.go
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/discovery/controller_test.go
  pkg/servicemesh/federation/exports/controller.go
  pkg/servicemesh/federation/federation.go
  pkg/servicemesh/federation/imports/controller.go
  pkg/servicemesh/federation/kube/controller.go
  pkg/servicemesh/federation/status/handler.go
Labels: okay to merge, size/L, maistra-2.4

#721 OSSM-2381: Use bookinfo 2.4 images
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: okay to merge, size/M

#723 Sync with 1.16
  go.mod
  go.sum
  istio.deps
  istioctl/cmd/analyze.go
  pilot/pkg/bootstrap/config_compare.go
  pilot/pkg/bootstrap/config_compare_test.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/features/pilot.go
  pilot/pkg/serviceregistry/kube/controller/controller.go
  pilot/pkg/serviceregistry/kube/controller/controller_test.go
  pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
  pilot/pkg/serviceregistry/kube/controller/endpoint_builder_test.go
  pilot/pkg/serviceregistry/kube/controller/multicluster.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
  pilot/pkg/serviceregistry/serviceentry/namespace_handler.go
  pilot/pkg/xds/endpoint_builder.go
  pkg/bootstrap/platform/gcp.go
  pkg/bootstrap/platform/gcp_test.go
  pkg/test/framework/components/echo/kube/templates/vm_deployment.yaml
  releasenotes/notes/42173.yaml
  releasenotes/notes/fix-42598.yaml
  releasenotes/notes/fix-42675.yaml
  releasenotes/notes/istioctl-analyze-revision.yaml
Labels: okay to merge, size/XL, merge strategy

#727 OSSM-2375 Prevent deadlock between multiNamespaceInformer.lock and namespaceSet.lock
  go.mod
  go.sum
Labels: okay to merge, size/S

#726 OSSM-2375 Prevent deadlock between multiNamespaceInformer.lock and namespaceSet.lock
  go.mod
  go.sum
  vendor/github.com/maistra/xns-informer/pkg/informers/informer.go
  vendor/modules.txt
Labels: okay to merge, size/S

#729 OSSM-2375 Prevent deadlock between multiNamespaceInformer.lock and namespaceSet.lock
  go.mod
  go.sum
  vendor/github.com/maistra/xns-informer/pkg/informers/informer.go
  vendor/maistra.io/api/client/versioned/clientset.go
  vendor/maistra.io/api/manifests/maistra.io_servicemeshcontrolplanes.yaml
  vendor/maistra.io/api/security/v1/trustbundle.pb.go
  vendor/maistra.io/api/security/v1/trustbundle_deepcopy.gen.go
  vendor/modules.txt
Labels: okay to merge, size/XXL

#730 OSSM-2430 update goutils to v1.1.1
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: okay to merge, size/M

#732 Sync with 1.16
  Makefile.core.mk
  README.md
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  istio.deps
  istioctl/pkg/verifier/verifier.go
  operator/cmd/mesh/shared.go
  pilot/pkg/autoregistration/controller.go
  pilot/pkg/model/push_context.go
  pilot/pkg/xds/proxy_dependencies.go
  pilot/pkg/xds/proxy_dependencies_test.go
  pkg/config/host/name.go
  releasenotes/notes/41912.yaml
  releasenotes/notes/42583.yaml
  releasenotes/notes/auto-passthrough-regression.yaml
Labels: okay to merge, size/L, merge strategy

#737 OSSM-3238: Fix deserializing trust bundles
  pilot/pkg/xds/tbds.go
  pkg/istio-agent/xds_proxy.go
  pkg/util/gogo/conversion.go
  pkg/util/gogo/conversion_test.go
Labels: okay to merge, size/L, jira/valid-reference
