Repository maistra/istio, pull requests merged in 2023-09, with the labels that each got.

#846 [maistra-2.5] OSSM-4646: Rebase CNI
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/install/binaries.go
  cni/pkg/install/binaries_test.go
  cni/pkg/install/cniconfig.go
  cni/pkg/install/install.go
  cni/pkg/install/install_test.go
  cni/pkg/install/kubeconfig.go
  cni/pkg/install/kubeconfig_test.go
  cni/pkg/plugin/iptables_linux.go
  cni/pkg/plugin/kubernetes.go
  cni/pkg/plugin/redirect.go
  cni/pkg/util/util.go
Labels: okay to merge, size/L, tide/merge-method-rebase

#850 OSSM-4763: Enable arm
  manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
  manifests/charts/istio-control/istio-discovery/values.yaml
  manifests/charts/istiod-remote/values.yaml
  pkg/kube/inject/testdata/inputs/custom-template.yaml.34.values.gen.yaml
  pkg/kube/inject/testdata/inputs/default.values.gen.yaml
  pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.10.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.14.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.17.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.values.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.values.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.8.values.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.values.gen.yaml
Labels: okay to merge, size/S

#840 OSSM-4648: Rebase IOR
  go.mod
  go.sum
  licenses/github.com/openshift/client-go/LICENSE
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/config/kube/ior/client.go
  pilot/pkg/config/kube/ior/controller.go
  pilot/pkg/config/kube/ior/fake.go
  pilot/pkg/config/kube/ior/ior.go
  pilot/pkg/config/kube/ior/ior_test.go
  pilot/pkg/features/pilot.go
  pilot/pkg/leaderelection/leaderelection.go
  pkg/kube/client.go
  pkg/kube/mock_client.go
  tests/integration/servicemesh/maistra/maistra.go
  tests/integration/servicemesh/managingroutes/main_test.go
  tests/integration/servicemesh/managingroutes/testdata/gateway.tmpl.yaml
  tests/integration/servicemesh/managingroutes/testdata/virtual-service.tmpl.yaml
  tests/integration/servicemesh/router/router.go
  tests/integration/servicemesh/router/testdata/route_crd.yaml
  tests/integration/servicemesh/router/testdata/router.yaml
  tests/integration/servicemesh/router/testdata/router_rbac.yaml
Labels: okay to merge, size/XXL, tide/merge-method-rebase

#853 OSSM-4793: Rebase dynamically-determined proxy UID/GID
  Makefile.core.mk
  istioctl/cmd/testdata/deployment/hello-with-proxyconfig-anno.yaml.injected
  istioctl/cmd/testdata/deployment/hello.yaml.injected
  istioctl/cmd/testdata/deployment/hello.yaml.iop.injected
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/gateway.yaml.injected
  pkg/kube/inject/testdata/inject/grpc-agent.yaml.injected
  pkg/kube/inject/testdata/inject/hello-tproxy.yaml.injected
  pkg/kube/inject/webhook.go
  pkg/kube/inject/webhook_test.go
Labels: okay to merge, size/L, tide/merge-method-rebase

#849 Fix IOR wrongly copying argocd internal annotation from Gateway to route
  pilot/pkg/config/kube/ior/controller.go
Labels: okay to merge, size/S, ok-to-test
