Repository maistra/istio, pull requests merged in 2024-05, with the labels that each got.

#992 [maistra-2.5] fix: TestReadSignedCertificate
  security/pkg/k8s/chiron/test-data/example-ca-cert.pem
  security/pkg/k8s/chiron/test-data/example-ca-cert2.pem
  security/pkg/k8s/chiron/utils_test.go
Labels: okay to merge, size/L, cherrypick/maistra-2.3, cherrypick/maistra-2.4

#991 OSSM-6403: Fix configuring UID/GID and iptables in TPROXY mode
  cni/pkg/plugin/redirect.go
  pkg/kube/inject/webhook.go
Labels: okay to merge, size/M

#996 [maistra-2.4] security: Fix outdated certificates
  security/pkg/k8s/chiron/controller_test.go
  security/pkg/k8s/chiron/test-data/example-ca-cert.pem
  security/pkg/k8s/chiron/test-data/example-ca-cert2.pem
  security/pkg/k8s/chiron/utils_test.go
Labels: okay to merge, size/L

#995 [maistra-2.4] OSSM-6403: Fix configuring UID/GID and iptables in TPROXY mode (#991)
  cni/pkg/plugin/redirect.go
  pkg/kube/inject/webhook.go
Labels: okay to merge, size/M

#1007 [maistra-2.3] security: Fix outdated certificates
  security/pkg/k8s/chiron/controller_test.go
  security/pkg/k8s/chiron/test-data/example-ca-cert.pem
  security/pkg/k8s/chiron/test-data/example-ca-cert2.pem
  security/pkg/k8s/chiron/utils_test.go
Labels: okay to merge, size/L

#1005 [maistra-2.6] Rebase CNI
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/install/binaries.go
  cni/pkg/install/binaries_test.go
  cni/pkg/install/cniconfig.go
  cni/pkg/install/install.go
  cni/pkg/install/install_test.go
  cni/pkg/install/kubeconfig.go
  cni/pkg/install/kubeconfig_test.go
  cni/pkg/util/util.go
Labels: okay to merge, size/L, tide/merge-method-rebase

#1011 [maistra-2.5] OSSM-6035 mod: update to protobuf v1.33
  go.mod
  go.sum
Labels: okay to merge, size/S
