Repository maistra/istio, pull requests merged in 2024-06, with the labels that each got.

#1018 Merge upstream tag '1.20.7'
  istio.deps
  pilot/pkg/networking/core/v1alpha3/route/route.go
  pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
  releasenotes/notes/fix-external-name.yaml
Labels: okay to merge, size/L, tide/merge-method-merge

#1025 Fix dnf update issue
  maistra/Dockerfile.istio-cni
  maistra/Dockerfile.proxyv2
  pilot/docker/Dockerfile.proxyv2
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_stream_8
Labels: okay to merge, size/S

#1023 Prevent non-error from showing up in CI logs
  common/scripts/kind_provisioner.sh
Labels: okay to merge, size/XS, cherrypick/maistra-2.4, cherrypick/maistra-2.6

#1022 OSSM-6615 Make sure IOR ignores services without selectors
  pilot/pkg/config/kube/ior/controller.go
  pilot/pkg/config/kube/ior/ior_test.go
  tests/integration/servicemesh/managingroutes/main_test.go
Labels: okay to merge, size/M, cherrypick/maistra-2.6

#1029 OSSM-6615 Make sure IOR ignores services without selectors
  pilot/pkg/config/kube/ior/controller.go
  pilot/pkg/config/kube/ior/ior_test.go
  tests/integration/servicemesh/managingroutes/main_test.go
Labels: okay to merge, size/M

#1019 OSSM-5698 Add GetProxyIDsFromPod() func for multitenant deployments
  pkg/kube/inject/inject.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-openshift-multitenant.yaml
  pkg/kube/inject/testdata/inject/hello-openshift-multitenant.yaml.injected
  pkg/kube/inject/testdata/inject/hello-openshift.yaml
  pkg/kube/inject/testdata/inject/hello-openshift.yaml.injected
  pkg/kube/inject/testdata/inputs/hello-openshift-multitenant.yaml.47.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-multitenant.yaml.47.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-multitenant.yaml.47.values.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.46.mesh.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.46.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.46.values.gen.yaml
  pkg/kube/inject/webhook.go
  pkg/platform/platform.go
Labels: okay to merge, size/XL

#1024 OSSM-6265: Bump quic-go v0.42.0
  go.mod
  go.sum
Labels: okay to merge, size/S

#1032 OSSM-6692: Add `StripPodUnusedFields` to pod informer used by federation controller
  pkg/servicemesh/federation/common/resources.go
Labels: okay to merge, size/XS

#1038 OSSM-6694 Fix federation's resourceManager.HasSynced() and flaky TestStatusManager
  pkg/servicemesh/federation/common/resources.go
  pkg/servicemesh/federation/status/handler.go
  pkg/servicemesh/federation/status/manager_test.go
Labels: okay to merge, size/S
