Repository maistra/istio, pull requests merged in 2024-03, with the labels that each got.

#947 Fix IOR wrongly copying argocd label from Gateway to route
  pilot/pkg/config/kube/ior/controller.go
Labels: okay to merge, size/S, ok-to-test, cherrypick/maistra-2.5

#958 OSSM-6079: Pass --resync flag to federation registry
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/federation.go
  tests/integration/servicemesh/federation/discovery/discovery_test.go
  tests/integration/servicemesh/federation/federation.go
  tests/integration/servicemesh/federation/ha/ha_test.go
Labels: okay to merge, size/S

#951 OSSM-5556: Set `net.ipv4.ip_unprivileged_port_start=0` in ingress and egress gateways
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-egress/templates/injected-deployment.yaml
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/injected-deployment.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
Labels: okay to merge, size/M

#962 [OSSM-6101][2.4] Fix a concurrent map write error
  pkg/kube/util.go
  releasenotes/notes/concurrent-map-write.yaml
Labels: okay to merge, size/S

#961 [OSSM-6101][2.5] Fix a concurrent map write error
  pkg/kube/util.go
  releasenotes/notes/concurrent-map-write.yaml
Labels: okay to merge, size/S

#964 Revert "OSSM-5556: Set `net.ipv4.ip_unprivileged_port_start=0` in ingress and egress gateways (#951)"
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-egress/templates/injected-deployment.yaml
  manifests/charts/gateways/istio-egress/values.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/injected-deployment.yaml
  manifests/charts/gateways/istio-ingress/values.yaml
Labels: okay to merge, size/M
