Repository maistra/istio, pull requests merged in 2024-07, with the labels that each got.

#1041 Ensure tests/integration/servicemesh/managingroutes/main_test.go can be run multiple times
  tests/integration/servicemesh/router/router.go
Labels: okay to merge, size/XS, cherrypick/maistra-2.4, cherrypick/maistra-2.5

#1044 Fix TestManagingGateways() and federation.CreateServiceMeshPeersOrFail()
  tests/integration/servicemesh/federation/federation.go
  tests/integration/servicemesh/managingroutes/main_test.go
Labels: okay to merge, size/XS

#1035 OSSM-6697 GatewayControllerMode integration test
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  operator/pkg/apis/istio/v1alpha1/values_types.proto
  tests/integration/servicemesh/gwcontrollermode/gwcontrollermode_test.go
Labels: okay to merge, size/L

#1050 OSSM-6812: Do not set cipher suites by default
  pilot/pkg/security/authn/utils/utils.go
  pilot/pkg/security/authn/utils/utils_test.go
  pilot/pkg/security/authn/v1beta1/policy_applier_test.go
Labels: okay to merge, size/S

#1051 OSSM-6830: update_bi_image_2.6
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
Labels: okay to merge, size/M

#1048 Use our proxy
  bin/init.sh
  istio.deps
  maistra/Dockerfile.istio-cni
  maistra/Dockerfile.pilot
  maistra/Dockerfile.proxyv2
  pilot/docker/Dockerfile.proxyv2
  pkg/config/security/security.go
  pkg/features/tls_cipher_suites.go
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_stream_9
  pkg/test/framework/components/echo/config.go
  pkg/test/framework/components/echo/kube/deployment.go
  prow/integ-suite-kind.sh
  prow/lib.sh
  tests/integration/security/external_ca/main_test.go
  tests/integration/security/sds_ingress/quic/ingress_test.go
  tools/docker.yaml
Labels: okay to merge, size/L
