Repository maistra/istio, pull requests merged in 2024-09, with the labels that each got.

#1062 Use rocky linux 9 instead of centos 9
  pilot/docker/Dockerfile.proxyv2
  pkg/test/echo/docker/Dockerfile.app_sidecar_rocky_linux_9
  pkg/test/framework/components/echo/kube/deployment.go
  prow/lib.sh
  tools/docker.yaml
Labels: okay to merge, size/M

#1061 [OSSM-3337] Support for IPv6 in the bookinfo mongo sample app
  samples/bookinfo/platform/kube/bookinfo-db.yaml
Labels: okay to merge, size/XS

#1063 OSSM-8099 Backport 2.6: handle draining endpoints for stateful header sessions (#52305)
  pilot/pkg/model/service.go
  pilot/pkg/networking/core/v1alpha3/cluster.go
  pilot/pkg/networking/grpcgen/cds.go
  pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Labels: okay to merge, size/S

#1060 OSSM-6578 backports/maistra-2.5 istio PR#49213
  pilot/pkg/networking/util/util.go
  pilot/pkg/networking/util/util_test.go
Labels: okay to merge, size/XS
