Repository maistra/istio, pull requests merged in 2024-04, with the labels that each got.

#977 OSSM-6177 Prevent nil pointer dereference when analysis is enabled and GatewayAPI is disabled
  pilot/pkg/config/kube/crdclient/client.go
Labels: okay to merge, size/XS

#976 OSSM-6261: Fix nil pointer dereference in istiod's `client.Shutdown()`
  pkg/kube/client.go
Labels: okay to merge, size/XS, ok-to-test

#978 OSSM-6289 Only watch required resources in analysis controller
  pkg/config/analysis/incluster/controller.go
Labels: okay to merge, size/S

#982 OSSM-6309: fix flaky test `federation/ha/TestDiscovery`
  tests/integration/servicemesh/federation/ha/ha_test.go
Labels: okay to merge, size/XS, cherrypick/maistra-2.4

#985 [maistra-2.4] OSSM-6079: Pass --resync flag to federation registry (#958)
  pkg/servicemesh/federation/discovery/controller.go
  pkg/servicemesh/federation/federation.go
  tests/integration/servicemesh/federation/discovery/discovery_test.go
  tests/integration/servicemesh/federation/federation.go
  tests/integration/servicemesh/federation/ha/ha_test.go
Labels: okay to merge, size/S

#986 [maistra-2.4] OSSM-6295: Copy all annotations and labels added by ArgoCD except `argocd.argoproj.io/instance` (#980)
  pilot/pkg/config/kube/ior/controller.go
  pilot/pkg/config/kube/ior/ior_test.go
Labels: okay to merge, size/L
